### PR TITLE
fix(meta): enhance postgres election client with timeouts and reconnection

### LINKED ISSUE #6267: Reconnect client when PostgreSQL connection is closed
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

In some cases, such as when `idle_session_timeout` is configured on the PostgreSQL server side, the database connection may be silently closed by the server if it has been idle for too long.

Currently, the client may continue to use a dropped connection without re-establishing it, which results in errors like:

```
Error { kind: Db, cause: Some(DbError { code: SqlState(E57P05), message: "terminating connection due to idle-session timeout", ... }) }
```

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
close #6267
## What's changed and what's your intention?

This PR enhances the reliability of the PostgreSQL election client by adding timeouts and reconnection mechanisms. The changes address two critical issues:

1. The election client not reconnecting after connection loss
2. Missing query/execution timeouts causing potential hangs

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/meta-srv/src/election/rds/postgres.rs [hunk 1]
```diff
@@ -349,6 +457,13 @@ impl Election for PgElection {
         }
     }
 
+    async fn reset_compaign(&self) {
```
Comment (v0y4g3r) [inline src/meta-srv/src/election/rds/postgres.rs]:
```suggestion
    async fn reset_campaign(&self) {
```

File: src/meta-srv/src/election/rds/postgres.rs [hunk 2]
```diff
@@ -349,6 +457,13 @@ impl Election for PgElection {
...
+        self.is_leader.store(false, Ordering::Relaxed);
+        if let Err(err) = self.pg_client.write().await.reset_client().await {
+            error!("Failed to reset client: {:?}", err);
```
Comment (v0y4g3r) [inline src/meta-srv/src/election/rds/postgres.rs]:
```suggestion
            error!(err; "Failed to reset client: {:?}");
```

File: src/meta-srv/src/election/rds/postgres.rs [hunk 3]
```diff
@@ -171,46 +161,169 @@ impl<'a> ElectionSqlFactory<'a> {
...
+            SqlExecutionTimeoutSnafu {
+                sql: sql.to_string(),
+                duration: self.execution_timeout,
+            }
+            .build()
+        })?;
+
+        result.with_context(|_| PostgresExecutionSnafu {
+            sql: sql.to_string(),
+        })
```
Comment (v0y4g3r) [inline src/meta-srv/src/election/rds/postgres.rs]: nit:
```suggestion
        result.context(PostgresExecutionSnafu { sql })
```

File: src/meta-srv/src/election/rds/postgres.rs [hunk 4]
```diff
@@ -171,46 +161,169 @@ impl<'a> ElectionSqlFactory<'a> {
...
```
Comment (v0y4g3r) [inline src/meta-srv/src/election/rds/postgres.rs]:
```suggestion
        result.context(PostgresExecutionSnafu { sql })
```

File: src/meta-srv/src/bootstrap.rs [hunk 5]
```diff
@@ -270,22 +268,35 @@ pub async fn metasrv_builder(
...
+
+            use crate::election::rds::postgres::ElectionPgClient;
+
+            let candidate_lease_ttl = Duration::from_secs(CANDIDATE_LEASE_SECS);
+            let execution_timeout = Duration::from_secs(META_LEASE_SECS);
+            let statement_timeout = Duration::from_secs(META_LEASE_SECS);
+            let meta_lease_ttl = Duration::from_secs(META_LEASE_SECS);
+
+            // We use a separate pool for election since we need a different session keep-alive idle time.
             let pool = create_postgres_pool(&opts.store_addrs).await?;
```
Comment (fengjiachun) [inline src/meta-srv/src/bootstrap.rs]: Can we share the pool with kvbackend?

Comment (v0y4g3r) [reply src/meta-srv/src/bootstrap.rs]: We should also set the `keepalive_idle` for connection pool to make sure all connecitons inside pool is valid.

- https://docs.rs/deadpool-postgres/latest/deadpool_postgres/struct.Config.html#structfield.keepalives
- https://docs.rs/deadpool-postgres/latest/deadpool_postgres/struct.Config.html#structfield.keepalives_idle

File: src/meta-srv/src/election.rs [hunk 6]
```diff
@@ -157,6 +157,11 @@ pub trait Election: Send + Sync {
     /// but only one can be the leader at a time.
     async fn campaign(&self) -> Result<()>;
 
+    /// Resets the compaign.
+    ///
+    /// Reset the client and the leader flag if needed.
+    async fn reset_compaign(&self) {}
```
Comment (fengjiachun) [inline src/meta-srv/src/election.rs]:
```suggestion
    async fn reset_campaign(&self) {}
```

File: src/meta-srv/src/election.rs [hunk 7]
```diff
@@ -157,6 +157,11 @@ pub trait Election: Send + Sync {
     /// but only one can be the leader at a time.
     async fn campaign(&self) -> Result<()>;
 
+    /// Resets the compaign.
```
Comment (fengjiachun) [inline src/meta-srv/src/election.rs]:
```suggestion
    /// Resets the campaign.
```

File: src/meta-srv/src/bootstrap.rs (hunk 5 above)
Comment (WenyXu) [reply src/meta-srv/src/bootstrap.rs]: Set default keepalive idle to 30s

**Review by v0y4g3r — APPROVED** [review]
LGTM
