### PR TITLE
fix: __field__ matcher on single value column 

### LINKED ISSUE #1779: PromQL query returns empty resultset when table contains a single field called value
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend

### What happened?

PromQL query returns empty resultset on a table that has a single field called `value`.

And If we add another random field, it returns correct result for `value`.

### What operating system did you use?

any

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

- Use gRPC interface to write into a table which has a single field called `value`.
- Query using PromQL like `host_load1{__field__="value"}`
- Get no result
- Add another column to this table, say `val`
- Query using PromQL `host_load1{__field__="value"}` again
- Mind blow

mind-blown

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

- Correct error text
- Avoid wrong table meta in distributed mode that leads to column not found error in plan stage

## Checklist

- [x]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)

Fixes #1779

### CODE REVIEW

File: src/table/src/metadata.rs [hunk 1]
```diff
@@ -162,13 +162,14 @@ impl TableMeta {
...
     pub fn field_column_names(&self) -> impl Iterator<Item = &String> {
-        let columns_schemas = &self.schema.column_schemas();
-        self.value_indices.iter().filter_map(|idx| {
-            let column = &columns_schemas[*idx];
-            if column.is_time_index() {
-                None
+        // `value_indices` is wrong under distributed mode. Use the logic copied from DESC TABLE
+        let columns_schemas = self.schema.column_schemas();
+        let primary_key_indices = &self.primary_key_indices;
+        columns_schemas.iter().enumerate().filter_map(|(i, cs)| {
```
Comment (etolbakov) [inline src/table/src/metadata.rs:168]: Probably I would go with separate filter and map steps here

Comment (waynexia) [reply src/table/src/metadata.rs]: Good point 👍
