### PR TITLE
fix: check for table scan before expanding

### LINKED ISSUE #2445: Support LogicalPlan::Insert to InsertRequest
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Our logic of processing prepared statement is converting them into LogicalPlan with placeholder. Thus all prepared statement will eventually becomes a logical plan, including `INSERT INTO`.

But we only support insert with gRPC request and SQL AST. This ticket requests another way that support converting logical plan to insert request

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

DistPlanner should only modify "queries" that need to access remote data. LogicalPlan also contains some DDL/DML plan which should be ignored by our planner

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
- https://github.com/GreptimeTeam/greptimedb/issues/2482
- closes #2445
- I'll add those test back after https://github.com/GreptimeTeam/greptimedb/pull/2484

### CODE REVIEW

**Review by killme2008 — APPROVED** [review]
LGTM 👍

**Comment by killme2008** [comment]
@waynexia There is a clippy warning.

**Comment by killme2008** [comment]
You have to update the sqlness result too. @waynexia

**Comment by killme2008** [comment]
@v0y4g3r @evenyag Please take a look

File: src/query/src/dist_plan/analyzer.rs [hunk 1]
```diff
@@ -44,13 +43,51 @@ impl AnalyzerRule for DistPlannerAnalyzer {
         plan: LogicalPlan,
         _config: &ConfigOptions,
     ) -> datafusion_common::Result<LogicalPlan> {
+        if !Self::is_query(&plan) {
+            return Ok(plan);
+        }
```
Comment (zhongzc) [inline src/query/src/dist_plan/analyzer.rs:48]: Then DML with heavy subquery cannot enjoy the rewriting?

File: tests/cases/distributed/explain/subqueries.result [hunk 2]
```diff
@@ -113,12 +113,11 @@ EXPLAIN INSERT INTO other SELECT i, 2 FROM integers WHERE i=(SELECT MAX(i) FROM
 | logical_plan | Dml: op=[Insert] table=[other]                                    |
 |              |   Projection: integers.i AS i, TimestampMillisecond(2, None) AS j |
 |              |     Inner Join: integers.i = __scalar_sq_1.MAX(integers.i)        |
-|              |       Projection: integers.i                                      |
-|              |         MergeScan [is_placeholder=false]                          |
+|              |       TableScan: integers projection=[i]                          |
 |              |       SubqueryAlias: __scalar_sq_1                                |
-|              |         Aggregate: groupBy=[[]], aggr=[[MAX(integers.i)]]         |
-|              |           Projection: integers.i                                  |
-|              |             MergeScan [is_placeholder=false]                      |
```
Comment (zhongzc) [inline tests/cases/distributed/explain/subqueries.result:121]: As I said before, the subquery here brings `MergeScan`, which pushes down `Projection` and `Aggregate`. Changing to `TableScan` can't even be executed.

Comment (zhongzc) [reply tests/cases/distributed/explain/subqueries.result:121]: How about making the push-down plan visible?

File: src/query/src/dist_plan/analyzer.rs (hunk 1 above)
Comment (waynexia) [reply src/query/src/dist_plan/analyzer.rs:48]: subquery in dml will be executed separately as a query in `execute_dml_subquery`

File: tests/cases/distributed/explain/subqueries.result (hunk 2 above)
Comment (waynexia) [reply tests/cases/distributed/explain/subqueries.result:121]: Nah there won't be an actual `TableScan`. We execute DML in two steps, but this isn't reflected in the explained plan.

>How about making the push-down plan visible?

This is on my list. I'm finding a way to display it prettier.

Comment (zhongzc) [reply tests/cases/distributed/explain/subqueries.result:121]: If so, explain of dml is different from the actual plan :\

Comment (zhongzc) [reply tests/cases/distributed/explain/subqueries.result:121]: > subquery in dml will be executed separately as a query in `execute_dml_subquery`

But it has the wrong logical plan. It still cannot be executed for a plan with `DistTable`. `execute_dml_subquery` doesn't do the plan rewriting.

Comment (waynexia) [reply tests/cases/distributed/explain/subqueries.result:121]: I made it too complicated. The only rule we need is to avoid the non-`TableScan` plan and apply all other cases

Comment (zhongzc) [reply tests/cases/distributed/explain/subqueries.result:121]: Sorry for my mistake, I always thought that the optimization of logical plan is done before execution, but in fact it is done during execution...
