### PR TITLE
test: add sqlness test for max execution time

### LINKED ISSUE #6514: Add Integration Tests for System Variables
### What type of enhancement is this?

Other

### What does the enhancement do?

Comment on https://github.com/GreptimeTeam/greptimedb/pull/6511#issuecomment-3059562806 .

Hi,@sunng87. If my understanding is incorrect, please give me some suggestions.

The federated.rs file currently handles MySQL federated query compatibility issues, but its check function only validates specific MySQL client query patterns.

I suggest creating a dedicated integration test module:

src/servers/tests/mysql/federated_query_test.rs
(or set_variable_test.rs if focusing specifically on SET variables)

Should this be a separate test file or part of existing integration tests?

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by codephage2020**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

Close #6514 

## What's changed and what's your intention?
add sqlness test for max_execution_time

 CC @sunng87 @WenyXu, Please review when you have time. Let me know if any adjustments are needed!

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

File: tests/cases/standalone/common/system/max_execution_time.sql
Comment (evenyag) [inline tests/cases/standalone/common/system/max_execution_time.sql:1]: MAX_EXECUTION_TIME is only available in MySQL protocol. You should set the `-- SQLNESS PROTOCOL MYSQL` hint.

https://github.com/GreptimeTeam/greptimedb/blob/582bcc3b146b80b29828fa04b935b7c6ca80498c/tests/cases/standalone/common/insert/mysql_insert.sql#L1

Comment (codephage2020) [reply tests/cases/standalone/common/system/max_execution_time.sql:1]: I added it in the latest update

Comment (codephage2020) [reply tests/cases/standalone/common/system/max_execution_time.sql:1]: But I found that the execution results of the same SQL statement in the terminal and SQLness are inconsistent.

Comment (codephage2020) [reply tests/cases/standalone/common/system/max_execution_time.sql:1]: For example, the following sentences
```sql
-- SQLNESS PROTOCOL MYSQL
SET MAX_EXECUTION_TIME = 1000;
-- SQLNESS PROTOCOL MYSQL
SELECT @@max_execution_time;
```
result in sqlness:
```txt
SET MAX_EXECUTION_TIME = 1000;

affected_rows: 0

-- SQLNESS PROTOCOL MYSQL
SELECT @@max_execution_time;

+-----------------------+
| @@max_execution_time; |
+-----------------------+
| 0                     |
+-----------------------+
```
result in terminal:
```txt
+-----------------------+
| @@max_execution_time; |
+-----------------------+
| 1000                  |
+-----------------------+
```

Comment (codephage2020) [reply tests/cases/standalone/common/system/max_execution_time.sql:1]: Thanks for your review @evenyag . 

I still don't know the reason for this. Could you give me a hint?

File: tests/cases/standalone/common/system/max_execution_time.result [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+
++-----------------------+
+| @@max_execution_time; |
++-----------------------+
+| 0                     |
++-----------------------+
+
+-- Test basic settings
+-- SQLNESS PROTOCOL MYSQL
+ -- Using global variable
```
Comment (evenyag) [inline tests/cases/standalone/common/system/max_execution_time.result]: The Indent is incorret
```suggestion
-- Using global variable
```

File: tests/cases/standalone/common/system/max_execution_time.sql
Comment (evenyag) [reply tests/cases/standalone/common/system/max_execution_time.sql:1]: There is a quick fix:
https://github.com/GreptimeTeam/greptimedb/blob/50148b25b5673b0eb2c5137b9f2bdb7f0a4222dd/src/servers/src/mysql/federated.rs#L171-L173

Modify the check above to
```rust
let var = var.trim_matches(|c| c == ' ' || c == ',' || c == ';');
```

The query received from the sqlness ends with `;`.

Comment (codephage2020) [reply tests/cases/standalone/common/system/max_execution_time.sql:1]: I noticed this change is causing CI failures in other tests. Do we still want to proceed with this modification? If so, I can help update the affected tests to maintain consistency.

File: tests/cases/standalone/common/system/max_execution_time.sql [hunk 2]
```diff
@@ -0,0 +1,90 @@
+-- Test default values
+-- SQLNESS PROTOCOL MYSQL
+SELECT @@max_execution_time;
+
+-- Test basic settings
+-- Using global variable
+-- SQLNESS PROTOCOL MYSQL
+SET MAX_EXECUTION_TIME = 1000;
+-- SQLNESS PROTOCOL MYSQL
```
Comment (killme2008) [inline tests/cases/standalone/common/system/max_execution_time.sql:10]: Love to add a blank line between SQLs.

Comment (codephage2020) [reply tests/cases/standalone/common/system/max_execution_time.sql:10]: Done

File: tests/cases/standalone/common/system/max_execution_time.sql
Comment (evenyag) [reply tests/cases/standalone/common/system/max_execution_time.sql:1]: Sure, thank you!
