### PR TITLE
fix: cli export "create table" with quoted names

### LINKED ISSUE #3681: cli export "create table" failed
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

start a standalone instance, create a table with dots in its name:

```sql
create table `a.b.c.d` (ts timestamp time index)
```

then follow our [docs](https://docs.greptime.com/user-guide/upgrade) to export the create table sql:

```text
./greptime cli export --addr '127.0.0.1:4001' --output-dir /tmp/greptimedb-export --target create-table
```

### What did you expect to see?

successful to export the create table sql

### What did you see instead?

error:

```text
2024-04-09T09:48:00.206017Z ERROR client::database: Failed to do Flight get, addr: 127.0.0.1:4001, code: Client specified an invalid argument, source: 0: Failed to do Flight get, code: Client specified an invalid argument
1: Invalid SQL, error: expect table name to be <catalog>.<schema>.<table>, <schema>.<table> or <table>, actual: greptime.public.a.b.c.d
2024-04-09T09:48:00.206154Z ERROR cmd::cli::export: Failed to export table greptime.public.a.b.c.d err=0: Failed to request database, sql: show create table greptime.public.a.b.c.d, at src/cmd/src/cli/export.rs:236:14
1: Failed to do Flight get, code: Client specified an invalid argument
2: Invalid SQL, error: expect table name to be <catalog>.<schema>.<table>, <schema>.<table> or <table>, actual: greptime.public.a.b.c.d
```

it's obviously that in cli export, we should quote the table name in the "show create table" sql.

### What operating system did you use?

macos

### What version of GreptimeDB did you use?

main

### Relevant log output and stack trace

_No response_

### PR DESCRIPTION
**Pull request by dimbtp**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

close #3681

## What's changed and what's your intention?

Solve the problem that running `cli export` with `--target create-table` fails when the `catalog/schema/table` names contain `.` (e.g. `a.b.c`).

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thank you!

**Comment by killme2008** [comment]
Good job! Could you add a test for it?

**Comment by dimbtp** [comment]
> Good job! Could you add a test for it?

@killme2008 
I did some investigations and tried following 2 approaches:

First use `std::process::Command::new` to spawn two threads, one is `standalone` server and another is `cli export` to test the function.
  Then I plan to create target database and table with quoted name (e.g. `test-export`.`a.b.c`), in locally I manually add it with `mysql` repl, but whether it's OK to do that in spawning a `mysql` thread?

I then switch to use `GreptimeDbStandalone` https://github.com/GreptimeTeam/greptimedb/blob/c00c1d95eed0b8e8035a206256207299fabd887d/tests-integration/src/standalone.rs#L42-L49, which can easily run sql but I don't know how to communicate `greptime cli export` with it. I think I need to craft `Export` first https://github.com/GreptimeTeam/greptimedb/blob/c00c1d95eed0b8e8035a206256207299fabd887d/src/cmd/src/cli/export.rs#L118-L125 then call `export_create_table`, but I don't make it.

**Comment by MichaelScofield** [comment]
@dimbtp I think you can refer to how the repl was tested before in "src/cmd/tests/cli.rs".

File: src/cmd/src/cli/export.rs [hunk 1]
```diff
@@ -226,7 +226,7 @@ impl Export {
     }
 
     async fn show_create_table(&self, catalog: &str, schema: &str, table: &str) -> Result<String> {
-        let sql = format!("show create table {}.{}.{}", catalog, schema, table);
+        let sql = format!("show create table '{}'.'{}'.'{}'", catalog, schema, table);
```
Comment (killme2008) [inline src/cmd/src/cli/export.rs:229]: Looks like we should use double quote or escape quote here?

Comment (dimbtp) [reply src/cmd/src/cli/export.rs:229]: IIUC, these three names are `the value of the identifier without quotes.`(https://docs.rs/sqlparser/latest/sqlparser/ast/struct.Ident.html#structfield.value)

Comment (tisonkun) [reply src/cmd/src/cli/export.rs:229]: @dimbtp do you test this function work well locally?

@killme2008 means SQL standard to quote identifier is by `"` instead of `'`. See https://stackoverflow.com/questions/2901453/sql-standard-to-escape-column-names.

**Review by tisonkun — CHANGES_REQUESTED** [review]
Shared concern.

File: src/cmd/src/cli/export.rs (hunk 1 above)
Comment (dimbtp) [reply src/cmd/src/cli/export.rs:229]: I noticed this issue before, but when using `mysql` connect to the greptimedb engine, I can freely use any quote style to execute the sql. And I notice that https://github.com/GreptimeTeam/greptimedb/blob/c00c1d95eed0b8e8035a206256207299fabd887d/src/cmd/src/cli/export.rs#L171-L177 use single quote, so I follow the same rule.

> do you test this function work well locally?

I test it locally and it works.

**Comment by MichaelScofield** [comment]
@dimbtp I mean you can use the same methods like how to use `Command` or how to handle the client in `src/cmd/tests/cli.rs`.

File: src/cmd/src/cli/export.rs (hunk 1 above)
Comment (tisonkun) [reply src/cmd/src/cli/export.rs:229]: Thanks for your info! I checked the underneath code in sqlparser-rs:

```rust
    /// Parse a simple one-word identifier (possibly quoted, possibly a keyword)
    pub fn parse_identifier(&mut self) -> Result<Ident, ParserError> {
        let next_token = self.next_token();
        match next_token.token {
            Token::Word(w) => Ok(w.to_ident()),
            Token::SingleQuotedString(s) => Ok(Ident::with_quote('\'', s)),
            Token::DoubleQuotedString(s) => Ok(Ident::with_quote('\"', s)),
            _ => self.expected("identifier", next_token),
        }
    }
```

It seems both single quote and double quote are supported, while it may not be quite identical with SQL standarad.

**Review by tisonkun — APPROVED** [review]
I'm OK with this. But may other reviewers would suggest how to add tests further.

File: src/cmd/src/cli/export.rs (hunk 1 above)
Comment (tisonkun) [reply src/cmd/src/cli/export.rs:229]: But using double quoted string would be more "formal". The example you refer to is about SQL string, not identifier.

I don't insist on this, although.

Comment (dimbtp) [reply src/cmd/src/cli/export.rs:229]: @MichaelScofield According to https://github.com/GreptimeTeam/greptimedb/blob/c00c1d95eed0b8e8035a206256207299fabd887d/src/cmd/src/cli.rs#L125-L130, `repl` function should wait a little bit as I don't observe too much progress on #2373

I have made a local test and prepare to push it for review.

Comment (MichaelScofield) [reply src/cmd/src/cli/export.rs:229]: @dimbtp we can make repl simple in that it does not need to talk to datanode, just frontend is enough. Cut down some functionalities. So the work is down to make it connect to frontend and submit the sql through its grpc client. Are you willing to take #2373?

Comment (tisonkun) [reply src/cmd/src/cli/export.rs:229]: I can see that the conversation is far beyond the scope of this patch.

If we agree that this patch is correct, I suggest we merge it and leave further test coverage or even improvement of test utils to follow-ups where @dimbtp probably world like to pick up.

```suggestion
        let sql = format!(r#"show create table "{}"."{}"."{}""#, catalog, schema, table);
```

I'd formally suggest this change to avoid some tricky coincides.

File: src/cmd/src/cli/export.rs [hunk 2]
```diff
@@ -417,3 +420,76 @@ fn split_database(database: &str) -> Result<(String, Option<String>)> {
         Ok((catalog.to_string(), Some(schema.to_string())))
     }
 }
+
+#[cfg(all(test, target_os = "linux"))]
```
Comment (dimbtp) [inline src/cmd/src/cli/export.rs:424]: I only test it on my local linux machine and it works.

File: src/cmd/src/cli/export.rs [hunk 3]
```diff
@@ -417,3 +420,76 @@ fn split_database(database: &str) -> Result<(String, Option<String>)> {
...
+            CREATE DATABASE "cli.export.create_table";
+        "#;
+        let res = database.sql(sql).await;
+        assert!(res.is_ok());
+
+        let sql = r#"
+            CREATE TABLE "cli.export.create_table"."a.b.c"(
+                ts TIMESTAMP,
+                TIME INDEX (ts)
+            ) engine=mito;
```
Comment (dimbtp) [inline src/cmd/src/cli/export.rs:458]: Create database with `complex` database name to avoid conflict with existing database, maybe check `if not exists`? Same for following `create table`.

File: src/cmd/src/cli/export.rs [hunk 4]
```diff
@@ -417,3 +420,76 @@ fn split_database(database: &str) -> Result<(String, Option<String>)> {
...
+    use std::path::PathBuf;
+    use std::process::{Command, Stdio};
+    use std::time::Duration;
+
+    use client::{Client, Database, DEFAULT_CATALOG_NAME, DEFAULT_SCHEMA_NAME};
+
+    #[tokio::test(flavor = "multi_thread")]
+    async fn test_export_create_table_with_quoted_names() {
+        let mut path = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
+        path.push("../../target/debug");
```
Comment (dimbtp) [inline src/cmd/src/cli/export.rs:435]: This work on local test, but according to `coverage ci`, this path is not correct. How to solve this?

File: src/cmd/src/cli/export.rs [hunk 5]
```diff
@@ -417,3 +420,76 @@ fn split_database(database: &str) -> Result<(String, Option<String>)> {
...
+        "#;
+        let res = database.sql(sql).await;
+        assert!(res.is_ok());
+
+        let _ = standalone.kill();
+
+        let output_file = output_dir
+            .path()
+            .join("greptime-cli.export.create_table.sql");
+        assert!(output_file.exists());
```
Comment (dimbtp) [inline src/cmd/src/cli/export.rs:493]: Is checking file exists enough? Do I need to check the exported content? Exported data may change in the future.

**Review by dimbtp — COMMENTED** [review]
@killme2008 @MichaelScofield @tisonkun A simple test and PTAL.

**Comment by dimbtp** [comment]
@killme2008 @MichaelScofield @tisonkun PTAL

**Comment by tisonkun** [comment]
@dimbtp the bin based test are super dirty. Since we already in the cmd crate, we can write more reliable and clean test cases.

@MichaelScofield perhaps the REPL test case can leverage the code I push in the last commit ..

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
However, still thanks a lot to nudge and drive this effort!

**Review by MichaelScofield — APPROVED** [review]
