### PR TITLE
fix: object store cache bug

### LINKED ISSUE #1458: bug: file leak in object store cache
### What type of bug is this?

Other

### What subsystems are affected?

Datanode

### What happened?

We already implemented an object store cache in #928 , but it has a potential issue.

The `LruCachePolicy` keeps all active cached items in memory, and if we restart the datanode, those items are lost.We don't recover the cached items from disk when initializing the LRU cache. The cache will be reconstructed by file accessing.

So if a file is not accessed after that at all, the file is leaked on disk forever and may consume too much disk consumption.

### What operating system did you use?

All os systems.

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

1. Enable the object store caching by setting `cache_path` in storage config when using s3 or OSS.
2. Write and read some data.
3. Restart the datanode(or standalone node).
4. The files in `cache_path` may leak.

### PR DESCRIPTION
**Pull request by killme2008**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Main changes:
* Recover LRU cache keys from local file cache path.
* Set `atomic_write_dir` for local file cache.
* Fixed reading cache file.
* Fixed writing cache file.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
Fix #1458

### CODE REVIEW

File: src/datanode/src/instance.rs [hunk 1]
```diff
@@ -409,14 +409,21 @@ fn create_object_store_with_cache(
...
-                })?;
-        let cache_layer = LruCacheLayer::new(Arc::new(cache_store), cache_capacity.0 as usize);
+        let atomic_temp_dir = format!("{path}/.tmp/");
+        clean_temp_dir(&atomic_temp_dir)?;
+        let cache_store = FsBuilder::default()
+            .root(path)
+            .atomic_write_dir(&atomic_temp_dir)
+            .build()
+            .with_context(|_| error::InitBackendSnafu {
+                config: store_config.clone(),
```
Comment (evenyag) [inline src/datanode/src/instance.rs:419]: question(out-of-topic): Is it necessary to put the config in the InitBackend error? The struct is quite large and we already have the error message from the source error.

File: src/object-store/src/cache_policy.rs [hunk 2]
```diff
@@ -31,19 +30,41 @@ use crate::metrics::{
...
     cache: Arc<C>,
     lru_cache: Arc<Mutex<LruCache<String, ()>>>,
 }
 
-impl<C: Accessor> LruCacheLayer<C> {
-    pub fn new(cache: Arc<C>, capacity: usize) -> Self {
-        Self {
+impl<C: Accessor + Clone> LruCacheLayer<C> {
+    pub async fn new(cache: Arc<C>, capacity: usize) -> Result<Self> {
+        let zelf = Self {
```
Comment (evenyag) [inline src/object-store/src/cache_policy.rs:41]: I think we could just use `layer` as the variable name. I only see the usage of `zelf` in our python script crate.

File: src/object-store/src/cache_policy.rs [hunk 3]
```diff
@@ -31,19 +30,41 @@ use crate::metrics::{
...
+        while let Some(entries) = pager.next().await? {
+            for entry in entries {
+                lru_cache.push(entry.path().to_string(), ());
+            }
         }
+
+        Ok(())
+    }
+
+    pub async fn lru_contains_key(&self, key: &str) -> bool {
```
Comment (evenyag) [inline src/object-store/src/cache_policy.rs:66]: Seems only tests use it
```suggestion
    #[cfg(test)]
    pub async fn lru_contains_key(&self, key: &str) -> bool {
```

Comment (killme2008) [reply src/object-store/src/cache_policy.rs:66]: It's in integration tests, we can't call it if it's tagged by ` #[cfg(test)]`.

File: src/datanode/src/instance.rs (hunk 1 above)
Comment (killme2008) [reply src/datanode/src/instance.rs:419]: Agree, let me remove it.

**Review by evenyag — APPROVED** [review]
LGTM

File: src/object-store/src/cache_policy.rs [hunk 4]
```diff
@@ -31,19 +30,41 @@ use crate::metrics::{
     OBJECT_STORE_LRU_CACHE_MISS,
 };
 
+#[derive(Clone)]
 pub struct LruCacheLayer<C> {
     cache: Arc<C>,
     lru_cache: Arc<Mutex<LruCache<String, ()>>>,
```
Comment (v0y4g3r) [inline src/object-store/src/cache_policy.rs:36]: Maybe `std::sync::RwLock` will be enough in this case.

Comment (v0y4g3r) [inline src/object-store/src/cache_policy.rs:36]: Maybe `std::sync::RwLock` will be enough in this case

**Comment by killme2008** [comment]
@v0y4g3r @evenyag  PTAL

File: src/object-store/src/cache_policy.rs [hunk 5]
```diff
@@ -163,7 +187,7 @@ impl<I: Accessor, C: Accessor> LayeredAccessor for LruCacheAccessor<I, C> {
         for file in cache_files {
             let _ = self.cache.delete(&file, OpDelete::new()).await;
         }
-        return self.inner.delete(&path, args).await;
+        return self.inner.delete(path, args).await;
```
Comment (evenyag) [inline src/object-store/src/cache_policy.rs:190]: nitpick
```suggestion
        self.inner.delete(path, args).await
```

**Review by v0y4g3r — APPROVED** [review]
LGTM
