### PR TITLE
fix: null first for part expr as logical expr

### LINKED ISSUE #7746: Repartition on metric physical table may cause duplicated rows
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Frontend, Datanode

### Minimal reproduce step

```sql
-- 1. Create physical metric table with 5 partitions
CREATE TABLE IF NOT EXISTS fuzz_repartition_metric_physical(
    ts TIMESTAMP(3) TIME INDEX,
    val DOUBLE,
    host STRING,
    PRIMARY KEY(host)
)
PARTITION ON COLUMNS(host) (
    host < '2Hmb',
    host >= '2Hmb' AND host < '5aaC',
    host >= '5aaC' AND host < '8tNn',
    host >= '8tNn' AND host < 'CCBO',
    host >= 'CCBO'
)
ENGINE=metric
WITH ("physical_metric_table" = "");

-- 2. Create logical metric table
CREATE TABLE amet(
    ts TIMESTAMP(3) TIME INDEX,
    val DOUBLE,
    `auT` STRING,
    PRIMARY KEY(`auT`)
)
ENGINE=metric
WITH ("on_physical_table" = "fuzz_repartition_metric_physical");

-- 3. Initial inserts
INSERT INTO amet (val, `auT`, ts) VALUES
(NULL, NULL, '2026-03-03 09:37:54.642+0000'),
(0.10097217862407382, 'quia', '2026-03-03 09:37:55.642+0000'),
(0.5617364109123318, NULL, '2026-03-03 09:37:56.642+0000');

-- 4. Repartition + concurrent inserts
ALTER TABLE fuzz_repartition_metric_physical MERGE PARTITION (
    host >= '5aaC' AND host < '8tNn',
    host >= '8tNn' AND host < 'CCBO'
);

INSERT INTO amet (ts) VALUES
('2026-03-03 09:37:57.642+0000'),
('2026-03-03 09:37:58.642+0000'),
('2026-03-03 09:37:59.642+0000');

INSERT INTO amet (ts) VALUES
('2026-03-03 09:38:00.642+0000'),
('2026-03-03 09:38:01.642+0000');

ALTER TABLE fuzz_repartition_metric_physical MERGE PARTITION (
    host < '2Hmb',
    host >= '2Hmb' AND host < '5aaC'
);

INSERT INTO amet (ts) VALUES
('2026-03-03 09:38:02.642+0000'),
('2026-03-03 09:38:03.642+0000'),
('2026-03-03 09:38:04.642+0000');

INSERT INTO amet (ts, val) VALUES
('2026-03-03 09:38:05.642+0000', NULL);

INSERT INTO amet (val, ts) VALUES
(0.6876966348855534, '2026-03-03 09:38:06.642+0000'),
(0.07711013139855483, '2026-03-03 09:38:07.642+0000');

ALTER TABLE fuzz_repartition_metric_physical SPLIT PARTITION (
    host < '5aaC'
) INTO (
    host < '4j7G',
    host >= '4j7G' AND host < '5aaC'
);

INSERT INTO amet (val, ts) VALUES
(0.9923739694362065, '2026-03-03 09:38:08.642+0000'),
(NULL, '2026-03-03 09:38:09.642+0000');

INSERT INTO amet (ts) VALUES
('2026-03-03 09:38:10.642+0000');

INSERT INTO amet (val, ts) VALUES
(NULL, '2026-03-03 09:38:11.642+0000');

ALTER TABLE fuzz_repartition_metric_physical MERGE PARTITION (
    host >= '5aaC' AND host < 'CCBO',
    host >= 'CCBO'
);

INSERT INTO amet (ts, val) VALUES
('2026-03-03 09:38:12.642+0000', 0.994035397543241),
('2026-03-03 09:38:13.642+0000', 0.4684296528169276),
('2026-03-03 09:38:14.642+0000', NULL);

INSERT INTO amet (`auT`, val, ts) VALUES
('incidunt', 0.06452630617091692, '2026-03-03 09:38:15.642+0000'),
('quibusdam', 0.6971632013964394, '2026-03-03 09:38:16.642+0000');

-- Validate
SELECT COUNT(*) FROM amet;
```

### What did you expect to see?

COUNT(*) = 23

### What did you see instead?

COUNT(*) = 39

### What operating system did you use?

doesn't matter

### What version of GreptimeDB did you use?

main

### Relevant log output and stack trace

```bash

```

### PR DESCRIPTION
**Pull request by discord9**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
fix #7746 
## What's changed and what's your intention?

as title, so after repartition, part col with null value wouldn't appear in multiple region's region scan, but only in the first region(order by partition expr), also null first is consistent with `src/datatypes/src/value.rs`'s def

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/partition/src/expr.rs [hunk 1]
```diff
@@ -301,28 +301,39 @@ impl PartitionExpr {
...
                     RestrictedOp::Lt => other_expr.lt(column_expr.clone()),
                     RestrictedOp::LtEq => other_expr.lt_eq(column_expr.clone()),
-                    RestrictedOp::Gt => other_expr.gt(column_expr.clone()),
-                    RestrictedOp::GtEq => other_expr.gt_eq(column_expr.clone()),
+                    RestrictedOp::Gt => {
+                        other_expr.gt(column_expr.clone()).or(column_expr.is_null())
+                    }
+                    RestrictedOp::GtEq => other_expr
+                        .gt_eq(column_expr.clone())
+                        .or(column_expr.is_null()),
```
Comment (evenyag) [inline src/partition/src/expr.rs:345]: Do we have a test case for `Int(value) > a OR a IS NULL`?

File: src/mito2/src/sst/parquet/file_range.rs [hunk 2]
```diff
@@ -739,7 +739,12 @@ impl RangeBase {
                     reason: "Failed to downcast to BooleanArray".to_string(),
                 })?;
 
-        Ok(boolean_array.values().clone())
+        let mut mask = boolean_array.values().clone();
+        if let Some(nulls) = boolean_array.nulls() {
+            mask = mask.bitand(nulls.inner());
+        }
+
+        Ok(mask)
```
Comment (waynexia) [inline src/mito2/src/sst/parquet/file_range.rs:748]: maybe add some context in comment with this code paragraph
