### PR TITLE
fix: create table after rename table

### LINKED ISSUE #892: cannot create table with a name which is occupied before
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode

### What happened?

For the following queries

```sql
CREATE TABLE t(i INTEGER, j BIGINT TIME INDEX);

ALTER TABLE t RENAME new_table;

SELECT * FROM t;

CREATE TABLE t(i INTEGER, j BIGINT TIME INDEX);
```

the third `SELECT` clause will report the table doesn't exist, but the fourth `CREATE` clause will fill due to table already exist

### What operating system did you use?

M1 Mac

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
By running the provided queries
```

### PR DESCRIPTION
**Pull request by e1ijah1**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Fix bug: table cannot be created after renaming

## Checklist

- [x]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
Fixes #892

### CODE REVIEW

File: src/datanode/src/tests/instance_test.rs [hunk 1]
```diff
@@ -392,6 +393,58 @@ async fn test_rename_table() {
 "
     .to_string();
     check_output_stream(output, expected).await;
+
+    execute_sql_in_db(&instance, "select * from demo", "db").await;
```
Comment (evenyag) [inline src/datanode/src/tests/instance_test.rs:397]: If any assertion in this test fails, the `#[should_panic]` attribute would still consider this test is passed. You could add a `try_execute_sql_in_db()` function and ensure its result is Err in this case.
```
async fn execute_sql_in_db() -> Output {
    try_execute_sql_in_db().await.unwrap()
}

async fn try_execute_sql_in_db() -> Result<Output> {}
```

**Review by evenyag — COMMENTED** [review]
Mostly LGTM. I leave a comment about the test.

File: src/datanode/src/tests/instance_test.rs (hunk 1 above)
Comment (e1ijah1) [reply src/datanode/src/tests/instance_test.rs]: A nice catch, thanks

**Review by evenyag — APPROVED** [review]

**Review by killme2008 — APPROVED** [review]
LGTM
