### PR TITLE
fix: wrong relation used in promql planner time cast

### LINKED ISSUE #7623: Tests are flaky and may fail intermittently
### What type of bug is this?

Other

### What subsystems are affected?

Other

### Minimal reproduce step

The issue can be reproduced by running the following command multiple times.
```
cargo nextest run integration_http_file_test::test_prom_http_api --nocapture
```

### What did you expect to see?

Test is passed.

### What did you see instead?

Test is not passed.
Error details:
```
  stderr ───

    thread 'integration_http_file_test::test_prom_http_api' (92258) panicked at tests-integration/tests/http.rs:1264:5:
    assertion `left == right` failed
      left: 400
     right: 200
    stack backtrace:
       0: __rustc::rust_begin_unwind
       1: core::panicking::panic_fmt
       2: core::panicking::assert_failed_inner
       3: core::panicking::assert_failed::<http::status::StatusCode, http::status::StatusCode>
       4: main::http::test_prom_http_api::{closure#0}
       5: main::integration_http_file_test::test_prom_http_api::{closure#0}
       6: <core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>> as core::future::future::Future>::poll
       7: <tokio::runtime::park::CachedParkThread>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>::{closure#0}
       8: <tokio::runtime::park::CachedParkThread>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
       9: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
      10: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>::{closure#0}
      11: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>::{closure#0}, ()>
      12: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
      13: <tokio::runtime::runtime::Runtime>::block_on_inner::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
      14: <tokio::runtime::runtime::Runtime>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
      15: main::integration_http_file_test::test_prom_http_api
      16: main::integration_http_file_test::test_prom_http_api::{closure#0}
      17: <main::integration_http_file_test::test_prom_http_api::{closure#0} as core::ops::function::FnOnce<()>>::call_once
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


```
The underlying cause is as follows:
```
{"status":"error","error":"Internal error during building DataFusion plan: No field named phy2.__tsid. Valid fields are demo_metrics_with_nanos.ts, demo_metrics_with_nanos.val, demo_metrics_with_nanos.__table_id, demo_metrics_with_nanos.__tsid, demo_metrics_with_nanos.idc.","errorType":"PlanQuery"}

```

### What operating system did you use?

arch linux

### What version of GreptimeDB did you use?

1088187b85ce8b8b3376fa9b31c6c0a8d3f57fb8

### Relevant log output and stack trace

```bash

```

### PR DESCRIPTION
**Pull request by fengys1996**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
Close #7623

### Issue

PromQL planner aliased the physical scan back to the logical table, but time cast/__tsid projections still used the physical table qualifier, producing phy2.__tsid and failing with “No field named …”.

### How to fix

Keep the current relation name in sync after aliasing so subsequent projections use the logical table qualifier.

### Tests

Added a demo_metrics_with_nanos query_range case in `test_prom_http_api` to cover the physical-table + nanos time + __tsid path.

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/query/src/promql/planner.rs [hunk 1]
```diff
@@ -1757,13 +1761,13 @@ impl PromPlanner {
                         expr: Box::new(self.create_time_index_column_expr()?),
                         data_type: ArrowDataType::Timestamp(ArrowTimeUnit::Millisecond, None),
                     })),
-                    relation: Some(scan_table_ref.clone()),
+                    relation: Some(curr_relation.clone()),
```
Comment (discord9) [inline src/query/src/promql/planner.rs]: how about change this to `logical_table_ref` instead as what `curr_relation` is is getting rather confusing

Comment (fengys1996) [reply src/query/src/promql/planner.rs]: `logical_table_ref` would be misleading: the value switches to the physical table during rewrite, then back to the logical name after alias. 😃

Comment (fengys1996) [reply src/query/src/promql/planner.rs]: how about `relation_ref`?

Comment (discord9) [reply src/query/src/promql/planner.rs]: I mean maybe not use a mutable variable might be more clear?

**Comment by discord9** [comment]
also sqlness for the fixed case?
