### PR TITLE
fix: remark region as inactive on leader changed

### LINKED ISSUE #2332: region failover procedure on metasrv leader changed
### What type of enhancement is this?

Other

### What does the enhancement do?

`DeactivateRegion` now marks a region as failed with a memory key:

https://github.com/GreptimeTeam/greptimedb/blob/6628f54b8908457887f2799528bb268b60cd25e5/src/meta-srv/src/procedure/region_failover/deactivate_region.rs#L65

But when metasrv's leader is working on region failover, it is possible for a leader change to occur.  So we need to persist the key to procedure store, when the new leader node re-executes this procedure, it can recover this key from the procedure store.

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by fengjiachun**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

If the meta leader node dies during the execution of the procedure, the new leader node needs to remark the failed region as "inactive" to prevent it from renewing the lease.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
Close #2332

### CODE REVIEW

File: src/meta-srv/src/procedure/region_failover/activate_region.rs [hunk 1]
```diff
@@ -37,13 +37,18 @@ use crate::service::mailbox::{Channel, MailboxReceiver};
 #[derive(Serialize, Deserialize, Debug)]
 pub(super) struct ActivateRegion {
     candidate: Peer,
+    // If the meta leader node dies during the execution of the procedure,
+    // the new leader node needs to remark the failed region as "inactive"
+    // to prevent it from renewing the lease.
+    remark_inactive_region: bool,
```
Comment (MichaelScofield) [inline src/meta-srv/src/procedure/region_failover/activate_region.rs:43]: I think it might be easier if we `register_inactive_region` when the failover procedure is recovered from `ActivateRegion` state. (The recovery of failover procedure is done in `RegionFailoverProcedure::from_json`.)

**Review by WenyXu — APPROVED** [review]

**Comment by fengjiachun** [comment]
@MichaelScofield PTAL

**Review by MichaelScofield — APPROVED** [review]
