### PR TITLE
fix!: not allowed to create column name same with keyword without quoted

### LINKED ISSUE #1299: Failed to execute query, invalid function "user"
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### What happened?

can't plan sql

### What operating system did you use?

macos

### Relevant log output and stack trace

error throwed at in planner.rs line 72:

```rust
let result = sql_to_rel.statement_to_plan(df_stmt).with_context(|_| {
```

### How can we reproduce the bug?

create table like this:

```sql
CREATE TABLE hello (
id bigint,
user STRING,
created_ts TIMESTAMP,
PRIMARY KEY(user),
TIME INDEX(created_ts)
)
```

then execute sql:

```sql
 select * from hello where user = 'foo';
```

not expected error:

ERROR 1815 (HY000): Failed to execute query: select * from hello where user = 'foo', source: Failed to plan statement, source: Cannot plan SQL: SELECT * FROM hello WHERE user = 'foo', source: Error during planning: Invalid function 'user'

### PR DESCRIPTION
**Pull request by MichaelScofield**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Fix #1299 

After some investigation, I found that #1299 is hard to find a walkaround, without breaking any compatibilities to pg or mysql. However, I did find that both pg and mysql not allowed to create column name same with keyword without quoted. So I think we should do the same.

After this PR, create table like this is invalid: `create table my_table(user string, i bigint time index);`, the error msg is:

ERROR 1815 (HY000): Failed to execute query: create table my_table(user string, i bigint time index), source: Failed to parse SQL, source: Syntax error, sql: create table my_table(user string, i bigint time index), source: sql parser error: Cannot use keyword 'user' as column name!

However, quote column name "user" with "", it's ok to execute: `create table my_table("user" string, i bigint time index);`

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

File: src/sql/src/parsers/create_parser.rs [hunk 1]
```diff
@@ -386,6 +387,16 @@ impl<'a> ParserContext<'a> {
         let parser = &mut self.parser;
 
         let name = parser.parse_identifier()?;
+        if name.quote_style.is_none() &&
+            // "ALL_KEYWORDS" are sorted.
+            ALL_KEYWORDS.binary_search(&name.value.to_uppercase().as_str()).is_ok()
+        {
+            return Err(ParserError::ParserError(format!(
+                "Cannot use keyword '{}' as column name!",
```
Comment (sunng87) [inline src/sql/src/parsers/create_parser.rs:395]:
```suggestion
                "Cannot use keyword '{}' as column name. Hint: add quotes to the name.",
```

**Review by sunng87 — COMMENTED** [review]
LGTM. But as tests indicates this can be a breaking change. We need to check our docs and examples to see if there are keywords used in column names.

**Comment by MichaelScofield** [comment]
checked the docs, only one place needs to change:

https://github.com/GreptimeTeam/docs/pull/296

**Comment by evenyag** [comment]
Back-quoted should be more common than double-quoted, maybe we need to test or add examples for this case.
```sql
create table my_table(`user` string, i bigint time index);
```

Many people use `timestamp` as the time index column name. This is a breaking change. cc @killme2008

**Review by evenyag — APPROVED** [review]
LGTM. Please check this breaking change @killme2008

**Comment by MichaelScofield** [comment]
using backtick "`" to quote identifier is not ANSI SQL standard, it's only mysql. pg does not support it. however, " and ' are.

**Comment by killme2008** [comment]
Yep, the sql-parser only accepts double-quoted or single-quoted strings as identifiers too.

This breaking change may be needed to update the docs. The ANSI Compatibility doc is still missing. https://docs.greptime.com/reference/sql/compatibility
