### PR TITLE
fix: don't raise an error when manifest directory is not created

### LINKED ISSUE #2288: can't use s3 in contabo.com https://contabo.com/en/object-storage/
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### What happened?

image

### What operating system did you use?

ubuntu

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

see this in slack
image

### PR DESCRIPTION
**Pull request by killme2008**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Return an empty result if the manifest directory is not created when scanning actions.

Try to fix #2288 

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)

Close #2288

### CODE REVIEW

File: src/mito2/src/manifest/storage.rs [hunk 1]
```diff
@@ -163,15 +163,20 @@ impl ManifestObjectStore {
...
     {
-        let streamer = self
-            .object_store
-            .list(&self.path)
-            .await
-            .context(OpenDalSnafu)?;
+        let streamer = match self.object_store.list(&self.path).await {
+            Ok(streamer) => streamer,
+            Err(e) if e.kind() == ErrorKind::NotFound => {
+                debug!("Manifest directory is not exists: {}", self.path);
```
Comment (v0y4g3r) [inline src/mito2/src/manifest/storage.rs:174]:
```suggestion
                debug!("Manifest directory does not exists: {}", self.path);
```

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Review by waynexia — APPROVED** [review]
LGTM. BTW, to fix #2288, you should open another PR for `develop` branch and do this change in mito1 as well

**Comment by killme2008** [comment]
> LGTM. BTW, to fix #2288, you should open another PR for `develop` branch and do this change in mito1 as well

The mito1 will be removed soon, so i don't want to fix it at this moment.
