### PR TITLE
fix: use full DDL of flow in information_schema.flows.flow_definition

### LINKED ISSUE #7687: The flow_definition from information_schema.flows is not complete
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Query Engine

### Minimal reproduce step

Comparing:

`SELECT flow_definition FROM information_schema.flows`

and

`SHOW CREATE FLOW <name>`

You can see the information_schema only carries the select query part of flow creation statement.

As we are going to provide flow export function based on the information_schema table #7679 , we will need full sql definition in this column.

### What did you expect to see?

The information_schema.flows.flow_definition should provide full create flow statement.

### What did you see instead?

It only has the select part.

```
select flow_definition from information_schema.flows;
                    flow_definition
--------------------------------------------------------
 SELECT                                                +
     http_method,                                      +
     request_url,                                      +
     COUNT(*) AS request_count,                        +
     date_bin('1 minutes'::INTERVAL, ts) AS time_window+
 FROM http_access_logs                                 +
 GROUP BY http_method, request_url, time_window
```

### What operating system did you use?

any

### What version of GreptimeDB did you use?

1.0

### Relevant log output and stack trace

```bash

```

### PR DESCRIPTION
**Pull request by sunng87**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

Fixes #7687 

## What's changed and what's your intention?

This patch builds full flow definition for information_schema.
It also update flake environment for recently introduced optional features.

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/catalog/src/system_schema/information_schema/flows.rs [hunk 1]
```diff
@@ -121,6 +126,50 @@ impl InformationSchemaFlows {
...
+            or_replace: false,
+            if_not_exists: true,
+            expire_after: flow_info.expire_after(),
+            eval_interval: flow_info.eval_interval(),
+            comment,
+            query,
+        };
+
+        Ok(stmt.to_string())
+    }
```
Comment (sunng87) [inline src/catalog/src/system_schema/information_schema/flows.rs:172]: This function is duplicated with the one in query/sql/create. But I can hardly find a way to use a common module for this.

I wonder if it's possible to simplify this?

**Comment by fengys1996** [comment]
@codex review
