### PR TITLE
fix: filter out outdated heartbeat

### LINKED ISSUE #1707: Filter out outdated heartbeats at Metasrv.
### What type of enhancement is this?

Refactor

### What does the enhancement do?

After the region failover is done, the distribution of region is changed. However, there might be heartbeats carrying outdated data, typically caused by network lagging, process awaking from dormant, or the heartbeats are just on the flight.

These heartbeats are not necessary and harmful, should be filtered out at Metasrv. We can compare the heartbeats info with the most recent global region placement metadata.

Also we need to remove the incorrect region ident keys in failure detect runner, too (by sending a control message).

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by fengjiachun**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

close #1707 

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

File: src/meta-srv/src/inactive_node_manager.rs [hunk 1]
```diff
@@ -94,17 +94,24 @@ impl<'a> InactiveNodeManager<'a> {
...
-            .filter(|(key, _)| !inactive_keys.contains(key))
+            .filter(|(key, region_id)| {
+                let is_active = !inactive_keys.contains(key);
+                if !is_active {
+                    inactive_region_ids.insert(*region_id);
+                }
+                is_active
+            })
             .map(|(_, region_id)| region_id)
             .collect::<Vec<_>>();
```
Comment (WenyXu) [inline src/meta-srv/src/inactive_node_manager.rs:112]: nitpick: 
```suggestion
        let (active_region_ids, inactive_region_ids): (Vec<Option<u64>>, Vec<Option<u64>>) =
            key_region_ids
                .into_iter()
                .map(|(key, region_id)| {
                    let is_active = !inactive_keys.contains(&key);
                    if is_active {
                        (Some(region_id), None)
                    } else {
                        (None, Some(region_id))
                    }
                })
                .unzip();

        let active_region_ids = active_region_ids.into_iter().flatten().collect();
        let inactive_region_ids = inactive_region_ids.into_iter().flatten().collect();
```

**Review by WenyXu — APPROVED** [review]

**Comment by fengjiachun** [comment]
@WenyXu PTAL

**Review by MichaelScofield — APPROVED** [review]
