### PR TITLE
fix: support duration to interval conversion in PostgreSQL protocol

### LINKED ISSUE #5911: Difference between timestamps does not work with (at least) psql client
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Query Engine

### Minimal reproduce step

```sql
public=> select '2025-04-14 20:42:19.021000'::timestamp - '2025-04-14 20:42:18.103000'::timestamp ;
ERROR:  Unsupported data type: DurationMillisecond, reason: not implemented
```

### What did you expect to see?

an interval

### What did you see instead?

an error

### What operating system did you use?

Archlinux

### What version of GreptimeDB did you use?

0.14

### Relevant log output and stack trace

```bash

```

### PR DESCRIPTION
**Pull request by v0y4g3r**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
- fix #5911
### Add Support for `Duration` Type in PostgreSQL Encoding

 - **Enhanced `encode_value` Functionality**: Updated `src/servers/src/postgres/types.rs` to support encoding of `Value::Duration` using `PgInterval`.
 - **Implemented `Duration` Conversion**: Added conversion logic from `Duration` to `PgInterval` in `src/servers/src/postgres/types/interval.rs`.
 - **Added Unit Tests**: Introduced tests for `Duration` to `PgInterval` conversion in `src/servers/src/postgres/types/interval.rs`.
 - **Updated SQL Test Cases**: Modified `tests/cases/standalone/common/types/timestamp/timestamp.sql` and `timestamp.result` to include tests for timestamp subtraction using PostgreSQL protocol.

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [x] I have written the necessary rustdoc comments.
- [x] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [x] API changes are backward compatible.
- [x] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/servers/src/postgres/types/interval.rs [hunk 1]
```diff
@@ -16,10 +16,18 @@ use std::fmt::Display;
...
 use common_time::interval::IntervalFormat;
-use common_time::{IntervalDayTime, IntervalMonthDayNano, IntervalYearMonth};
+use common_time::timestamp::TimeUnit;
+use common_time::{Duration, IntervalDayTime, IntervalMonthDayNano, IntervalYearMonth};
 use pgwire::types::ToSqlText;
 use postgres_types::{to_sql_checked, FromSql, IsNull, ToSql, Type};
 
+use crate::error;
+
+const SECONDS_PER_MONTH: i64 = 24 * 6 * 6 * 3044;
```
Comment (MichaelScofield) [inline src/servers/src/postgres/types/interval.rs:26]: "3044" needs a doc

**Review by MichaelScofield — APPROVED** [review]

File: src/servers/src/postgres/types/interval.rs (hunk 1 above)
Comment (v0y4g3r) [reply src/servers/src/postgres/types/interval.rs:27]: fixed in 3df2c7021
