### PR TITLE
fix: throw errors instead of ignoring

### LINKED ISSUE #5796: [CRITICAL] Add column after altering table options causing crashes
### What type of bug is this?

Crash

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

1. Start GreptimeDB
```bash
docker run -p 127.0.0.1:4000-4003:4000-4003 \
  -v "$(pwd)/greptimedb:/greptimedb_data" \
  --name greptime --rm \
  greptime/greptimedb:latest standalone start \
  --http-addr 0.0.0.0:4000 \
  --rpc-bind-addr 0.0.0.0:4001 \
  --mysql-addr 0.0.0.0:4002 \
  --postgres-addr 0.0.0.0:4003
```

2. Run Following SQL
```sql

mysql> CREATE TABLE test(i INTEGER, j TIMESTAMP TIME INDEX);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into test values(1,1);
Query OK, 1 row affected (0.01 sec)

mysql> select * from test;
+------+----------------------------+
| i    | j                          |
+------+----------------------------+
|    1 | 1970-01-01 00:00:00.001000 |
+------+----------------------------+
1 row in set (0.06 sec)

mysql> alter table test set ttl='1d';
Query OK, 0 rows affected (0.01 sec)

mysql> select * from test;
+------+----------------------------+
| i    | j                          |
+------+----------------------------+
|    1 | 1970-01-01 00:00:00.001000 |
+------+----------------------------+
1 row in set (0.00 sec)

mysql> ALTER TABLE test ADD COLUMN "IdC" STRING default 'idc';
Query OK, 0 rows affected (0.01 sec)

mysql> select * from test;

```

### What did you expect to see?

Show the row inserted

### What did you see instead?

```
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    8
Current database: *** NONE ***

ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    8
Current database: *** NONE ***

ERROR 2013 (HY000): Lost connection to MySQL server during query
```

### What operating system did you use?

NA

### What version of GreptimeDB did you use?

v0.13

### Relevant log output and stack trace

```bash
2025-03-28T08:44:12.849376Z ERROR RegionInvoker::handle_query:handle_read:exec_query_plan:create_physical_plan: common_telemetry::panic_hook: panicked at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-schema-53.4.0/src/schema.rs:382:10:
index out of bounds: the len is 2 but the index is 2 backtrace=   0: common_telemetry::panic_hook::set_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: datafusion_expr::logical_plan::plan::TableScan::try_new
  10: datafusion_optimizer::optimize_projections::optimize_projections
  11: datafusion_optimizer::optimize_projections::rewrite_projection_given_requirements
  12: datafusion_optimizer::optimize_projections::optimize_projections
  13: <datafusion_optimizer::optimize_projections::OptimizeProjections as datafusion_optimizer::optimizer::OptimizerRule>::rewrite
  14: datafusion_optimizer::optimizer::optimize_plan_node
  15: datafusion_optimizer::optimizer::Optimizer::optimize
  16: query::datafusion::DatafusionQueryEngine::create_physical_plan::{{closure}}::{{closure}}
  17: query::datafusion::DatafusionQueryEngine::exec_query_plan::{{closure}}::{{closure}}
  18: query::datafusion::DatafusionQueryEngine::exec_query_plan::{{closure}}
  19: <query::datafusion::DatafusionQueryEngine as query::query_engine::QueryEngine>::execute::{{closure}}
  20: datanode::region_server::RegionServer::handle_read::{{closure}}::{{closure}}
  21: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  22: <frontend::instance::standalone::RegionInvoker as common_meta::node_manager::Datanode>::handle_query::{{closure}}
  23: <frontend::instance::region_query::FrontendRegionQueryHandler as query::region_query::RegionQueryHandler>::do_get::{{closure}}
  24: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
  25: <common_recordbatch::RecordBatchStreamWrapper<S> as futures_core::stream::Stream>::poll_next
  26: <common_recordbatch::adapter::DfRecordBatchStreamAdapter as futures_core::stream::Stream>::poll_next
  27: datafusion_physical_plan::stream::RecordBatchReceiverStreamBuilder::run_input::{{closure}}
  28: tokio::runtime::task::raw::poll
  29: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  30: tokio::runtime::scheduler::multi_thread::worker::Context::run
  31: tokio::runtime::context::runtime::enter_runtime
  32: tokio::runtime::scheduler::multi_thread::worker::run
  33: tokio::runtime::task::core::Core<T,S>::poll
  34: tokio::runtime::task::harness::Harness<T,S>::poll
  35: tokio::runtime::blocking::pool::Inner::run
  36: std::sys::backtrace::__rust_begin_short_backtrace
  37: core::ops::function::FnOnce::call_once{{vtable.shim}}
  38: std::sys::pal::unix::thread::Thread::new::thread_start
  39: <unknown>
  40: clone
 panic.file="/root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-schema-53.4.0/src/schema.rs" panic.line=382 panic.column=10
Well, this is embarrassing.

GreptimeDB had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-b2746097-48ae-4d88-82df-ff16135c5d76.toml". Submit an issue or email with the subject of "GreptimeDB Crash Report" and include the report as an attachment.

- Homepage: https://github.com/GreptimeTeam/greptimedb/discussions

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
```

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
fixes #5796
#5798

## What's changed and what's your intention?

This PR addresses issue #5796, which was caused by discrepancies in version handling between the datanode and metasrv. When a user first invokes the `ALTER TABLE ... OPTIONS` statement, the datanode does not increment the schema version, whereas the metasrv does. This results in a version mismatch between the metadata in metasrv and the datanode. During the processing of an alter request, the datanode checks the schema version from metasrv, and if they are inconsistent, it throws an "outdated request" error. However, the previous procedure implementation ignored the schema version mismatch error from the datanode (outdated request), leading to a situation where metasrv assumes the datanode has successfully updated the schema. Consequently, this results in a schema inconsistency between the datanode and metasrv.

This PR enhances the alter table procedure by 

- Throwing errors instead of silently ignoring them. 
- Remove schema version check in the datanode alter handling.

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/common/meta/src/ddl/utils.rs [hunk 1]
```diff
@@ -182,6 +183,62 @@ pub fn extract_region_wal_options(
...
+        return MultipleResults::Ok;
+    } else if !retryable_results.is_empty()
+        && !ok_results.is_empty()
+        && non_retryable_results.is_empty()
+    {
+        return MultipleResults::PartialRetryable(retryable_results.into_iter().next().unwrap());
+    }
+
+    // non_retryable_results.len() > 0
+    MultipleResults::PartialNonRetryable(non_retryable_results.into_iter().next().unwrap())
```
Comment (fengjiachun) [inline src/common/meta/src/ddl/utils.rs:239]: Add an error log and print the details of errors when there are `non retriable results`.

Comment (WenyXu) [reply src/common/meta/src/ddl/utils.rs:253]: Resolved in [15cad34](https://github.com/GreptimeTeam/greptimedb/pull/5792/commits/15cad345f59c2bb7561a255d97a120c21eed6bae)

**Review by fengjiachun — APPROVED** [review]
LGTM

File: src/common/meta/src/error.rs [hunk 2]
```diff
@@ -766,7 +780,9 @@ impl ErrorExt for Error {
             | SerializeToJson { .. }
             | DeserializeFromJson { .. } => StatusCode::Internal,
 
-            ValueNotExist { .. } => StatusCode::Unexpected,
+            NoLeader { .. } => StatusCode::TableUnavailable,
+
+            ValueNotExist { .. } | ConsistencyGuardConflict { .. } => StatusCode::Unexpected,
```
Comment (killme2008) [inline src/common/meta/src/error.rs:785]: I think `ConsistencyGuardConflict` should return `TableUnavailable` too.

File: src/common/meta/src/ddl/utils.rs [hunk 3]
```diff
@@ -182,6 +184,75 @@ pub fn extract_region_wal_options(
     Ok(region_wal_options)
 }
 
+pub enum MultipleResults {
```
Comment (killme2008) [inline src/common/meta/src/ddl/utils.rs:187]: Describe this enum in detail.

File: src/common/meta/src/key.rs [hunk 4]
```diff
@@ -62,6 +62,14 @@
 //! 13. Topic name to region map key `__topic_region/{topic_name}/{region_id}`
 //!     - Mapping {topic_name} to {region_id}
 //!
+//! 14. Consistency guard key `__consistency_guard/{resource_type}/{resource_id}`
```
Comment (killme2008) [inline src/common/meta/src/key.rs:65]: Why do we need another lock when we already have the table lock?

File: src/frontend/src/heartbeat.rs [hunk 5]
```diff
@@ -93,6 +93,12 @@ impl HeartbeatTask {
                 match resp_stream.message().await {
                     Ok(Some(resp)) => {
                         debug!("Receiving heartbeat response: {:?}", resp);
+                        if let Some(msg) = resp.mailbox_message.as_ref() {
```
Comment (killme2008) [inline src/frontend/src/heartbeat.rs:96]: The log may be annoying.

File: tests/cases/standalone/common/alter/alter_table.result [hunk 6]
```diff
@@ -192,3 +192,46 @@ DROP TABLE phy;
 
 Affected Rows: 0
 
+CREATE TABLE grpc_latencies (
```
Comment (killme2008) [inline tests/cases/standalone/common/alter/alter_table.result:195]: This test likely doesn't cover the intended fixes; it's just a simple alter test. To properly cover this, we need a test that simulates both successful and failed alter region requests in distributed mode, that would make sense.

**Comment by killme2008** [comment]
Did we discuss the solution carefully, or was it just another attempt? @fengjiachun @evenyag @v0y4g3r

File: src/common/meta/src/error.rs (hunk 2 above)
Comment (WenyXu) [reply src/common/meta/src/error.rs:785]: The upper layer will retry if the status is `TableUnavailable`, which is not the expected behavior. When a `ConsistencyGuardConflict` occurs, users need to manually repair the table using a repair procedure (we will provide later)

File: src/common/meta/src/ddl/utils.rs (hunk 3 above)
Comment (WenyXu) [reply src/common/meta/src/ddl/utils.rs:194]: resolved in [0bca295](https://github.com/GreptimeTeam/greptimedb/pull/5792/commits/0bca29552c3fc24d307306ff11406db1f492cc4f)

File: src/frontend/src/heartbeat.rs (hunk 5 above)
Comment (WenyXu) [reply src/frontend/src/heartbeat.rs]: removed in [96b4e41](https://github.com/GreptimeTeam/greptimedb/pull/5792/commits/96b4e410d09b34f5e5b4a679018bf68ab59652c6)

File: src/common/meta/src/key.rs (hunk 4 above)
Comment (WenyXu) [reply src/common/meta/src/key.rs:65]: The key is used to indicate an ongoing operation on a specific resource, ensuring metadata consistency between datanodes and the metadata. If any potential operation failure (e.g., a partial datanode returns success) could lead to metadata inconsistency, any attempt to alter the table will be rejected until the metadata is consistent again, which may require manual table repair.

Comment (killme2008) [reply src/common/meta/src/key.rs:65]: My question is why we can just use the existing table metadata key?

```
//! 5. Table name key: `__table_name/{catalog_name}/{schema_name}/{table_name}`
//!     - The value is a [TableNameValue] struct; it contains the table id.
//!     - Used in the table name to table id lookup.
```

File: tests/cases/standalone/common/alter/alter_table.result (hunk 6 above)
Comment (WenyXu) [reply tests/cases/standalone/common/alter/alter_table.result:195]: The test covered in #5796. However, the PR also introduces some features(i.e., the consistency guard) from #5798. The proper tests you mentioned will be introduced in subsequent PRs.

File: src/common/meta/src/key.rs (hunk 4 above)
Comment (WenyXu) [reply src/common/meta/src/key.rs:65]: I prefer not to mix them together.

Comment (killme2008) [reply src/common/meta/src/key.rs:65]: I don't think it's a mix. Remember that we designed the table metadata key to protect the table's metadata and ensure its consistency.  And this is a consistent issue, am I right?

File: src/common/meta/src/key.rs [hunk 7]
```diff
@@ -174,6 +174,7 @@ pub const KAFKA_TOPIC_KEY_PREFIX: &str = "__topic_name/kafka";
 // The legacy topic key prefix is used to store the topic name in previous versions.
 pub const LEGACY_TOPIC_KEY_PREFIX: &str = "__created_wal_topics/kafka";
 pub const TOPIC_REGION_PREFIX: &str = "__topic_region";
+pub const CONSISTENCY_POISON_PREFIX: &str = "__consistency_poison";
```
Comment (fengjiachun) [inline src/common/meta/src/key.rs:177]: Can it be removed?

Comment (WenyXu) [reply src/common/meta/src/key.rs]: removed

File: src/common/meta/src/ddl/utils.rs [hunk 8]
```diff
@@ -182,6 +184,82 @@ pub fn extract_region_wal_options(
...
+    AllRetryable(Error),
+    AllNonRetryable(Error),
+}
+
+/// Handles the results of alter region requests.
+///
+/// For partial success, we need to check if the errors are retryable.
+/// If all the errors are retryable, we return a retryable error.
+/// Otherwise, we return the first error.
+pub fn handle_multiple_results<T: Debug>(results: Vec<Result<T>>) -> MultipleResults {
```
Comment (evenyag) [inline src/common/meta/src/ddl/utils.rs:207]: We may handle empty results for safety.

File: src/common/procedure/src/error.rs [hunk 9]
```diff
@@ -276,6 +282,15 @@ impl Error {
...
         Error::External {
             source: BoxedError::new(err),
+            clean_poisons: false,
+        }
+    }
+
+    /// Creates a new [Error::External] error from source `err` and clean poisons.
+    pub fn external_and_clean_poisons<E: ErrorExt + Send + Sync + 'static>(err: E) -> Error {
+        Error::External {
+            source: BoxedError::new(err),
```
Comment (evenyag) [inline src/common/procedure/src/error.rs:292]: nitpick: Can we box the err before invoking this method? Then we don't need to make this function generic.

File: src/common/meta/src/ddl/alter_table.rs [hunk 10]
```diff
@@ -140,28 +164,50 @@ impl AlterTableProcedure {
...
-                            // As this procedure has locked the table, the only reason for this error
-                            // is procedure is succeeded before and is retrying.
-                            return Err(add_peer_context_if_needed(datanode)(err));
-                        }
-                    }
-                    Ok(())
+                    requester
+                        .handle(request)
+                        .await
+                        .map_err(add_peer_context_if_needed(datanode))
```
Comment (evenyag) [inline src/common/meta/src/ddl/alter_table.rs:170]: Do we need to log the error here?

**Review by evenyag — APPROVED** [review]
