### PR TITLE
fix: disable ansi contorl char when stdout is redirected

### LINKED ISSUE #3323: greptime still prints terminal sequences when the log is redirected to a file
### What type of bug is this?

Other

### What subsystems are affected?

Other

### Minimal reproduce step

start the server, redirect the log to a file

### What did you expect to see?

n/a

### What did you see instead?

The log file contains:
```
^[[2m2024-02-19T08:03:49.205531Z^[[0m ^[[32m INFO^[[0m ^[[2mcommon_procedure::local^[[0m^[[2m:^[[0m LocalManager start to recover
^[[2m2024-02-19T08:03:49.205638Z^[[0m ^[[32m INFO^[[0m ^[[2mcommon_procedure::local^[[0m^[[2m:^[[0m LocalManager finish recovery, cost: 0ms
^[[2m2024-02-19T08:03:49.205738Z^[[0m ^[[32m INFO^[[0m ^[[2mfrontend::instance^[[0m^[[2m:^[[0m Starting service: POSTGRES_SERVER
^[[2m2024-02-19T08:03:49.205829Z^[[0m ^[[32m INFO^[[0m ^[[2mservers::server^[[0m^[[2m:^[[0m Starting POSTGRES_SERVER at 127.0.0.1:4003
^[[2m2024-02-19T08:03:49.205965Z^[[0m ^[[32m INFO^[[0m ^[[2mservers::server^[[0m^[[2m:^[[0m Postgres server started at 127.0.0.1:4003
^[[2m2024-02-19T08:03:49.206119Z^[[0m ^[[32m INFO^[[0m ^[[2mfrontend::instance^[[0m^[[2m:^[[0m Starting service: OPENTSDB_SERVER
```

### What operating system did you use?

FreeBSD 14.0

### What version of GreptimeDB did you use?

rev. 29f11d7b7e

### Relevant log output and stack trace

_No response_

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Check if stdout is redirected for the logging layer. And disable ansi control char if it's redirected to a non-tty file.

log with `greptime standalone start`:
image

log with `greptime standalone start > greptime.log`
image

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

## Refer to a related PR or issue link (optional)

Closes #3323

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thank you!

This should supersede #3331?

**Comment by waynexia** [comment]
> Thank you!
> 
> This should supersede #3331?

I've reverted the change to the file logging layer. Now it won't conflict with #3331. But I'm not sure if we need #3331 for [this reason](https://github.com/GreptimeTeam/greptimedb/pull/3331#issuecomment-1953432930)

File: src/common/telemetry/src/logging.rs [hunk 1]
```diff
@@ -132,22 +132,27 @@ pub fn init_global_logging(
...
+        Some(
+            Layer::new()
+                .with_writer(stdout_writer)
+                .with_ansi(atty::is(atty::Stream::Stdout)),
+        )
     } else {
         None
     };
 
-    // JSON log layer.
```
Comment (waynexia) [inline src/common/telemetry/src/logging.rs:144]: The JSON format layer is no longer exist

**Comment by tisonkun** [comment]
> But I'm not sure if we need https://github.com/GreptimeTeam/greptimedb/pull/3331 for https://github.com/GreptimeTeam/greptimedb/pull/3331#issuecomment-1953432930

Although, it is _not_ harmful to always set `with_ansi(false)` for file logger (so even for `err_file_logging_layer`). fmt_layer always check this flag, and when logging to file, we don't need it anyway.

**Review by MichaelScofield — APPROVED** [review]
