### PR TITLE
fix: correct unicode representation for jsonb_to_string

### LINKED ISSUE #7808: Imcompatible unicode encoding in json_to_string output
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend

### Minimal reproduce step

In psql:

```
public=> create table testtable(t timestamp time index, v json);
OK 0
public=> insert into testtable values (0, '{"a":123}');
OK 1
public=> insert into testtable values (0, '{"a":"\u2024"}');
OK 1
public=> insert into testtable values (2, '{"a":"\u2024"}');
OK 1
public=> select t, json_to_string(v) from testtable;
             t              | json_to_string(testtable.v)
----------------------------+-----------------------------
 1970-01-01 00:00:00.000000 | {"a":"․"}
 1970-01-01 00:00:00.002000 | {"a":"․"}
(2 rows)

public=> insert into testtable values (4, '{"a":"\u2028"}');
OK 1
public=> select t, json_to_string(v) from testtable;
             t              | json_to_string(testtable.v)
----------------------------+-----------------------------
 1970-01-01 00:00:00.000000 | {"a":"․"}
 1970-01-01 00:00:00.002000 | {"a":"․"}
 1970-01-01 00:00:00.004000 | {"a":"\u{2028}"}
(3 rows)

```

### What did you expect to see?

The unicode character should be in this form: `\u2028` 

### What did you see instead?

It's in the rust form `\u{2028}`

bun or python will not parse this:

```
SyntaxError: JSON Parse error: "\u{202" is not a valid unicode escape


```

### What operating system did you use?

any

### What version of GreptimeDB did you use?

HEAD

We had relevant fix in #7520 but it didn't fix all cases.

### PR DESCRIPTION
**Pull request by sunng87**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

Fixes #7808

## What's changed and what's your intention?

Correct unicode representation for json string. 

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/datatypes/src/types/json_type.rs [hunk 1]
```diff
@@ -405,16 +405,16 @@ pub fn jsonb_to_string(val: &[u8]) -> Result<String> {
 /// Converts a json type value to serde_json::Value
 pub fn jsonb_to_serde_json(val: &[u8]) -> Result<serde_json::Value> {
     let json_string = jsonb_to_string(val)?;
-    jsonb_string_to_serde_value(&json_string)
+    let normalized = jsonb_string_to_serde_value(&json_string)?;
+    serde_json::Value::from_str(&normalized).context(DeserializeSnafu { json: normalized })
```
[the remark this answers is not in the document]
Comment (avifenesh) [reply src/datatypes/src/types/json_type.rs]: Same as metrics discussion — the LLM agent can inject the token value directly. Pre-check handles the missing token case.

File: src/datatypes/src/types/json_type.rs [hunk 2]
```diff
@@ -396,7 +396,7 @@ pub fn jsonb_to_string(val: &[u8]) -> Result<String> {
     match jsonb::from_slice(val) {
         Ok(jsonb_value) => {
             let serialized = jsonb_value.to_string();
-            Ok(serialized)
+            fix_unicode_point(&serialized)
```
Comment (MichaelScofield) [inline src/datatypes/src/types/json_type.rs:399]: This makes every call to `jsonb_to_string` will do a regex `replace_all`, regardless of whether the `val` contains Rust-style Unicode code, which is less often. It occurs to my mind that jsonb value can directly convert to serde_json value, maybe jsonb already take care of the Rust-style Unicode code escape?

Comment (sunng87) [reply src/datatypes/src/types/json_type.rs:399]: The root cause of this issue is jsonb's `to_string` doesn't generate correct unicode style. It outputs `\u{xxxx}` instead of `\uxxxx`. So for any `jsonb.to_string()` we will use this patch function to fix before shipping to client.

Comment (MichaelScofield) [reply src/datatypes/src/types/json_type.rs:399]: Yes, I mean is it possible to not use the `jsonb.to_string()`? Let the `jsonb_value` convert to serde_json value directly, and convert to string thereafter.

Comment (sunng87) [reply src/datatypes/src/types/json_type.rs:399]: Just tested, when constructing serde_json value from jsonb_value, it copies the string value to serde_json value directly, so the `u{xxxx}` style was kept. Since there is no deserialization process, it won't cause any error.

```rust
#[test]
fn test_unicode_point_json_string() {
    let value = r#"{"a": "Tomcat \u2008"}"#;
    let jsonb = jsonb::parse_value(value.as_bytes()).unwrap().to_vec();
    let result = jsonb::to_serde_json(jsonb.as_ref()).unwrap().to_string();
    assert_eq!(result, value);
}

thread 'types::json_type::tests::test_unicode_point_json_string' (1223921) panicked at src/datatypes/src/types/json_type.rs:474:9:
    assertion `left == right` failed
      left: "{\"a\":\"Tomcat \u{2008}\"}"
     right: "{\"a\": \"Tomcat \\u2008\"}"
```

**Review by MichaelScofield — APPROVED** [review]
