### PR TITLE
fix: respect node id and metasrv addr in config file

### LINKED ISSUE #537: Run distribution mode error if using config file
### What type of bug is this?

Configuration

### What subsystems are affected?

Datanode

### What happened?

greptimedb-operator will allocate node id(from [initializer](https://github.com/GreptimeTeam/greptimedb-operator/pull/63)) to datanode by using config file. For example, operator will start datanode as following command:

```
greptime datanode start --metasrv-addr=basic.default:3002 --mysql-addr=0.0.0.0:3306 --config-file=/etc/datanode/datanode.yaml
```

For the latest version, there is some configuration error in [here](https://github.com/GreptimeTeam/greptimedb/blob/develop/src/cmd/src/datanode.rs#L97-L104): the current code only use command line args. If we provide `node-id` in config file, the final `opts` won't get such config. Then the above start command will crash.

### What operating system did you use?

macOS 

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
$ cargo run -- datanode start --metasrv-addr=basic.default:3002 --mysql-addr=0.0.0.0:3306 --config-file=./config/datanode.example.toml            
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/greptime datanode start '--metasrv-addr=basic.default:3002' '--mysql-addr=0.0.0.0:3306' --config-file=./config/datanode.example.toml`
2022-11-16T08:21:54.327954Z  INFO cmd::datanode: Datanode start command: StartCommand {
    node_id: None,
    rpc_addr: None,
    mysql_addr: Some(
        "0.0.0.0:3306",
    ),
    metasrv_addr: Some(
        "basic.default:3002",
    ),
    config_file: Some(
        "./config/datanode.example.toml",
    ),
}
2022-11-16T08:21:55.968218Z ERROR greptime: Fatal error occurs! err.msg=Missing config, msg: Missing node id option err.code=InvalidArguments err.backtrace= 0 backtrace::backtrace::libunwind::trace::hcdfd8b20f85c976d

```
```

### PR DESCRIPTION
**Pull request by v0y4g3r**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?
When datanode starts, it reads metasrv addr and node id from command line args to determine running mode, but it does not respect config in config files. This PR is to fix this by:

First read all options from config file,  override node id/metasrv addr with command line args if present. After all opts are set, checks if options are valid, 
- if mode is standalone, node id can be left absent.
- if mode is distribitede, node id must be present.

metasrv is no longer mandatory, since it has a default value.

## Checklist

- [x]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
 Fixes #537

### CODE REVIEW

File: src/datanode/src/mock.rs [hunk 1]
```diff
@@ -91,7 +91,7 @@ impl Instance {
     pub async fn with_mock_meta_server(opts: &DatanodeOptions, meta_srv: MockInfo) -> Result<Self> {
         let object_store = new_object_store(&opts.storage).await?;
         let log_store = create_local_file_log_store(opts).await?;
-        let meta_client = Arc::new(mock_meta_client(meta_srv, opts.node_id).await);
+        let meta_client = Arc::new(mock_meta_client(meta_srv, 42).await);
```
Comment (fengjiachun) [inline src/datanode/src/mock.rs:94]: Why hard-code？

File: src/cmd/src/datanode.rs [hunk 2]
```diff
@@ -93,31 +93,20 @@ impl TryFrom<StartCommand> for DatanodeOptions {
...
-                return MissingConfigSnafu {
-                    msg: "Missing node id option",
-                }
-                .fail();
+        if let Some(node_id) = cmd.node_id {
+            opts.node_id = Some(node_id);
+        }
+
+        if let Some(meta_addr) = cmd.metasrv_addr {
+            opts.meta_client_opts.metasrv_addr = meta_addr;
```
Comment (zyy17) [inline src/cmd/src/datanode.rs:101]: should we set `opts.metasrv_addr`?

Comment (v0y4g3r) [reply src/cmd/src/datanode.rs:101]: `DatanodeOptions:: metasrv_addr ` is already removed since it's redundant.

File: src/datanode/src/mock.rs (hunk 1 above)
Comment (v0y4g3r) [reply src/datanode/src/mock.rs:94]: I found this will break some test if node id is harcoded.

**Review by fengjiachun — APPROVED** [review]
LGTM

**Review by zyy17 — APPROVED** [review]
LGTM
