### PR TITLE
fix(metric-engine): group DDL requests

### LINKED ISSUE #5619: Failed to create a logical table on a physical table when number of partitions exceeds the number of datanodes
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Distributed Cluster

### Minimal reproduce step

1. Set up a GreptimeDB cluster.
2. Create a physical table with multiple partitions (where the number of partitions exceeds the number of datanodes).
3. Create a logical table based on the physical table.

### What did you expect to see?

The logical table should be created

### What did you see instead?

ERROR 1210 (HY000): (InvalidArguments): Region options are conflicted

### What operating system did you use?

doesn't matter

### What version of GreptimeDB did you use?

0.12.0

### Relevant log output and stack trace

```bash

```

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
close #5619 
## What's changed and what's your intention?

This PR fixes #5619 by grouping DDL requests to ensure that requests within a single group belong to the same physical table.

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/metric-engine/src/engine/alter.rs [hunk 1]
```diff
@@ -54,37 +53,52 @@ impl MetricEngineInner {
             let (region_id, request) = requests.pop().unwrap();
             self.alter_physical_region(region_id, request).await?;
         } else {
-            self.alter_logical_regions(requests, extension_return_value)
-                .await?;
+            let grouped_requests =
```
Comment (killme2008) [inline src/metric-engine/src/engine/alter.rs:56]: Maybe we can add a fast path when region number is 1.

**Review by killme2008 — APPROVED** [review]

File: src/metric-engine/src/engine/alter.rs (hunk 1 above)
Comment (WenyXu) [reply src/metric-engine/src/engine/alter.rs]: Resolved in [4467745](https://github.com/GreptimeTeam/greptimedb/pull/5628/commits/4467745e80f468e98ea349aceb86382b8dd94cff)

**Review by MichaelScofield — APPROVED** [review]

File: src/metric-engine/src/engine/create/validate.rs [hunk 2]
```diff
@@ -12,46 +12,44 @@
...
-/// Returns extracted physical region id from the first request.
-pub fn validate_create_logical_regions(
-    requests: &[(RegionId, RegionCreateRequest)],
-) -> Result<RegionId> {
-    let (_, request) = requests.first().unwrap();
-    let first_physical_region_id_raw = request
+use crate::error::{MissingRegionOptionSnafu, ParseRegionIdSnafu, Result};
+
+/// Groups the create logical regions requests by physical region id.
+pub fn group_create_logical_regions_requests_by_physical_region_id(
```
Comment (fengjiachun) [inline src/metric-engine/src/engine/create/validate.rs:25]:
```suggestion
pub fn group_logical_region_requests_by_physical_region_id(
```

File: src/metric-engine/src/engine/create/validate.rs [hunk 3]
```diff
@@ -12,46 +12,44 @@
...
-///
-/// Returns extracted physical region id from the first request.
-pub fn validate_create_logical_regions(
-    requests: &[(RegionId, RegionCreateRequest)],
-) -> Result<RegionId> {
-    let (_, request) = requests.first().unwrap();
-    let first_physical_region_id_raw = request
+use crate::error::{MissingRegionOptionSnafu, ParseRegionIdSnafu, Result};
+
+/// Groups the create logical regions requests by physical region id.
```
Comment (fengjiachun) [inline src/metric-engine/src/engine/create/validate.rs:24]: Maybe we need to rename the file, 'validate' is no longer appropriate.

File: src/metric-engine/src/engine/alter.rs [hunk 4]
```diff
@@ -54,37 +53,70 @@ impl MetricEngineInner {
...
+                        extension_return_value,
+                    )
+                    .await?;
+                }
+            }
         }
         Ok(0)
     }
 
+    fn group_alter_logical_regions_requests_by_physical_region_id(
```
Comment (fengjiachun) [inline src/metric-engine/src/engine/alter.rs:84]:
```suggestion
    fn group_logical_region_requests_by_physical_region_id(
```

File: src/metric-engine/src/engine/create/validate.rs (hunk 3 above)
Comment (WenyXu) [reply src/metric-engine/src/engine/create/validate.rs]: Removed in [9828cbb](https://github.com/GreptimeTeam/greptimedb/pull/5628/commits/9828cbbc6acf95407dc2c705689dcf39b76faacd)
