### PR TITLE
fix: refreshing Dashboard returns 404

### LINKED ISSUE #1552: Dashboard in binary can not be refreshed.
### What type of bug is this?

Other

### What subsystems are affected?

Other

### What happened?

- Dashboard in GreptimeDB binary only recognizes `localhost:4000/dashboard`. 
- If we input `localhost:4000/dashboard/` or `localhost:4000/dashboard/query` as URL, it will not work.
- As a result, the page can not be refreshed.

Not sure if this can be fixed. I assume the problem is caused by the server's way to find the correct `index.html` and its location.

### What operating system did you use?

Mac OS Montery 12.6 ARM

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

1. Start GreptimeDB with pre-built binary.
2. Visit `http://localhost:4000/dashboard`
3. Click refresh button.

### PR DESCRIPTION
**Pull request by MichaelScofield**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

fix #1552 

Now "/dashboard", "/dashboard/" and "/dashboard/query" all works as expected. However, "/dashboard/not/existed" still returns 404.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Review by sunng87 — APPROVED** [review]

File: src/servers/src/http/dashboard.rs [hunk 1]
```diff
@@ -27,18 +28,32 @@ use crate::error::{BuildHttpResponseSnafu, Result};
 pub struct Assets;
 
 pub(crate) fn dashboard() -> Router {
-    Router::new().fallback(static_handler)
+    Router::new()
+        .route("/", routing::get(static_handler).post(static_handler))
+        .route("/*x", routing::get(static_handler).post(static_handler))
```
Comment (evenyag) [inline src/servers/src/http/dashboard.rs:33]: What does `/*x` mean?

**Review by evenyag — APPROVED** [review]

File: src/servers/src/http/dashboard.rs (hunk 1 above)
Comment (sunng87) [reply src/servers/src/http/dashboard.rs:33]: It means all remaining parts a assigned to variable `x`. For instance, in `/book/12/name`, `x` is `book/12/name`
