### PR TITLE
fix: concurrent rename two table to same name may cause override

### LINKED ISSUE #1369: Race condition when rename two tables to the same name
### What type of bug is this?

Data corruption

### What subsystems are affected?

Datanode

### What happened?

When renaming tables, `MemorySchemaProvider::rename_table` does not check if the target table name already exists. 

https://github.com/GreptimeTeam/greptimedb/blob/da66138e809975e1f88b80cd8cb0457de1946e8a/src/catalog/src/local/memory.rs#L325-L337

If two rename operation runs concurrently to rename two tables to the same name, the later operation will override previous table.

### What operating system did you use?

NA

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
NA
```

### PR DESCRIPTION
**Pull request by v0y4g3r**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?
fix concurrent rename two table to same name may cause override

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)

fixes #1369

### CODE REVIEW

**Review by waynexia — APPROVED** [review]
🫨

**Review by evenyag — COMMENTED** [review]
Does the LocalCatalogManager have a similar issue?
https://github.com/GreptimeTeam/greptimedb/blob/716bde8f041e3f8060b1a1138acca3a9993c138f/src/catalog/src/local/manager.rs#L415-L442

Looks like we should acquire the register lock and check whether the new table exists

**Comment by v0y4g3r** [comment]
> Does the LocalCatalogManager have a similar issue?
> 
> https://github.com/GreptimeTeam/greptimedb/blob/716bde8f041e3f8060b1a1138acca3a9993c138f/src/catalog/src/local/manager.rs#L415-L442
> 
> Looks like we should acquire the register lock and check whether the new table exists

Maybe we should first rename table in memory and then write to system catalog table like this:
```rust
        //...

        let renamed = schema
            .rename_table(&request.table_name, request.new_table_name)
            .is_ok();
        if renamed {
            // rename table in system catalog
            self.system
                .register_table(
                    catalog_name.clone(),
                    schema_name.clone(),
                    request.new_table_name.clone(),
                    request.table_id,
                    engine,
                )
                .await?;
        }
        Ok(renamed)
```

File: src/catalog/src/local/manager.rs [hunk 1]
```diff
@@ -427,19 +427,23 @@ impl CatalogManager for LocalCatalogManager {
...
-        Ok(schema
-            .rename_table(&request.table_name, request.new_table_name)
-            .is_ok())
+
+        let renamed = schema
+            .rename_table(&request.table_name, request.new_table_name.clone())
+            .is_ok();
+        if renamed {
+            // rename table in system catalog
+            self.system
```
Comment (evenyag) [inline src/catalog/src/local/manager.rs:436]: correctness: register_table may fail, then the state in memory is inconsistent with the system table, so I think the correct steps are:
- acquire the register_lock to avoid other threads registering a table with the same new name
- check whether the table with the new name exists
- register the table to the system catalog table (overwrite the table entry)
- rename the table in the schema (should always success)

**Review by evenyag — APPROVED** [review]
