### PR TITLE
fix: import tokio-metrics and tokio-metrics-collector

### LINKED ISSUE #5263: need import tokio_metrics and tokio_metrics_collector
### What type of bug is this?

Other

### What subsystems are affected?

Other

### Minimal reproduce step

just git clone main branch and make 

### What did you expect to see?

I just want to compile successfully.

### What did you see instead?

error[E0433]: failed to resolve: use of undeclared crate or module `tokio_metrics`
   --> src/common/runtime/src/runtime.rs:215:19
    |
215 |     let monitor = tokio_metrics::RuntimeMonitor::new(handle);
    |                   ^^^^^^^^^^^^^ use of undeclared crate or module `tokio_metrics`

error[E0433]: failed to resolve: use of undeclared crate or module `tokio_metrics_collector`
   --> src/common/runtime/src/runtime.rs:216:21
    |
216 |     let collector = tokio_metrics_collector::RuntimeCollector::new(monitor, name);
    |                     ^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `tokio_metrics_collector`

   Compiling async-lock v3.4.0
For more information about this error, try `rustc --explain E0433`.
error: could not compile `common-runtime` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
make: *** [build] Error 101

### What operating system did you use?

Mac OS X 15.1 ARM

### What version of GreptimeDB did you use?

0.11.1

### Relevant log output and stack trace

```bash
error[E0433]: failed to resolve: use of undeclared crate or module `tokio_metrics`
   --> src/common/runtime/src/runtime.rs:215:19
    |
215 |     let monitor = tokio_metrics::RuntimeMonitor::new(handle);
    |                   ^^^^^^^^^^^^^ use of undeclared crate or module `tokio_metrics`

error[E0433]: failed to resolve: use of undeclared crate or module `tokio_metrics_collector`
   --> src/common/runtime/src/runtime.rs:216:21
    |
216 |     let collector = tokio_metrics_collector::RuntimeCollector::new(monitor, name);
    |                     ^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `tokio_metrics_collector`

   Compiling async-lock v3.4.0
For more information about this error, try `rustc --explain E0433`.
error: could not compile `common-runtime` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
make: *** [build] Error 101
```

### PR DESCRIPTION
**Pull request by chenmortal**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

close #5263 

## What's changed and what's your intention?
- just fix bug to compile successfully

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

**Comment by v0y4g3r** [comment]
Thanks, can you make `tokio-metrics` and `tokio-metrics-collector` optional like this since they are only used when `tokio_unstable` flag is switched on?

```
[target.'cfg(tokio_unstable)'.dependencies]
tokio-metrics = { version = "0.3" }
tokio-metrics-collector = { version = "0.2" }
```

**Comment by sunng87** [comment]
Another suggestion, only to put dependencies in workspace Cargo.toml when it's used in multiple workspace members. In this case, you can simply define it in Cargo.toml from runtime module.

File: src/servers/src/hint_headers.rs [hunk 1]
```diff
@@ -25,6 +28,16 @@ pub const HINT_KEYS: [&str; 5] = [
 
 pub(crate) fn extract_hints<T: ToHeaderMap>(headers: &T) -> Vec<(String, String)> {
     let mut hints = Vec::new();
+    if let Some(value_str) = headers.get(HINTS_KEY) {
```
Comment (v0y4g3r) [inline src/servers/src/hint_headers.rs:31]: Is this intentional included in this PR? cc @fengjiachun

Comment (chenmortal) [reply src/servers/src/hint_headers.rs]: I'm very sorry for the incorrect operations on git.

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Review by sunng87 — APPROVED** [review]
