### PR TITLE
fix(mito): fix region drop task runs multiple times but never clean the dir

### LINKED ISSUE #2501: The background task drop table multiple times
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode, Datanode

### What happened?

The background task drop table multiple times

Screenshot 2023-09-26 at 19 07 38

### What operating system did you use?

Ubuntu 23.04

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

1. Create a table
2. Insert data
3. Flush data
4. Drop the table

### PR DESCRIPTION
**Pull request by evenyag**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?
This PR fixes the following issues while dropping a region
- background later drop task never exits until it exceeds max retry times
- the dropping region map keeps the region that references all SSTs thus we can't purge them. This PR reset the `Version` so the region releases the references to SSTs and purges them.

It also adds a test to check whether the region directory is removed as expected.

## Checklist

- [x]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
closes #2501

### CODE REVIEW

**Review by waynexia — APPROVED** [review]

**Review by fengjiachun — APPROVED** [review]
LGTM

File: src/mito2/src/worker/handle_drop.rs [hunk 1]
```diff
@@ -85,32 +97,41 @@ async fn later_drop_task(
...
         "Failed to GC region dir {} after {} retries, giving up",
         region_path, MAX_RETRY_TIMES
     );
+
+    false
 }
 
 // TODO(ruihang): place the marker in a separate dir
+/// Removes region dir if there is no parquet files, returns whether the directory is removed.
 pub(crate) async fn remove_region_dir_once(
```
Comment (killme2008) [inline src/mito2/src/worker/handle_drop.rs:131]: Adds `#[must_use]` would be better.
