### PR TITLE
fix(table-procedure): Open table in RegisterCatalog state

### LINKED ISSUE #1614: CreateTableProcedure panicked at  Option::unwrap()
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### What happened?

The procedure panicked while recovering

### What operating system did you use?

Linux

### Relevant log output and stack trace

```bash
2023-05-19T08:14:25.125396Z  INFO common_procedure::local: LocalManager start to recover
70
2023-05-19T08:14:25.259393Z  INFO common_procedure::local: Recover root procedure table-procedure::CreateTableProcedure-db421319-0ae9-4bb8-ae21-479380c6bc6d, step: 2
69
2023-05-19T08:14:25.259777Z  INFO common_procedure::local::runner: Runner table-procedure::CreateTableProcedure-db421319-0ae9-4bb8-ae21-479380c6bc6d starts
68
2023-05-19T08:14:25.261520Z ERROR common_telemetry::panic_hook: panicked at 'called `Option::unwrap()` on a `None` value', src/table-procedure/src/create.rs:258:14 backtrace=   0: <unknown>
 panic.file="src/table-procedure/src/create.rs" panic.line=258 panic.column=14
41
thread 'bg-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/table-procedure/src/create.rs:258:14
40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
39
2023-05-19T08:14:25.262934Z ERROR common_procedure::local::runner: Procedure db421319-0ae9-4bb8-ae21-479380c6bc6d exits unexpectedly
```

### How can we reproduce the bug?

Restart the db during creating table

### PR DESCRIPTION
**Pull request by evenyag**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?
Open the created table in the `CreateTable::RegisterCatalog` state so the procedure can execute correctly after recovery.

To test this case, it adds the following helper functions to execute the procedure without the procedure manager
- execute_parent_procedure
- execute_procedure_once

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
fix #1614

### CODE REVIEW

File: src/common/procedure-test/src/lib.rs [hunk 1]
```diff
@@ -52,3 +64,53 @@ pub async fn execute_procedure_until_done(procedure: &mut BoxedProcedure) {
...
+            false
+        }
+        Status::Done => true,
+    }
+}
+
+/// Executes a procedure until it returns [Status::Suspended] or [Status::Done].
+///
+/// Returns `Some` if it returns [Status::Suspended] or `None` if it returns [Status::Done].
+pub async fn execute_parent_procedure(
```
Comment (killme2008) [inline src/common/procedure-test/src/lib.rs:97]: The function name is confusing. But I can't find a better name.

**Review by killme2008 — APPROVED** [review]
LGTM

File: src/common/procedure-test/src/lib.rs (hunk 1 above)
Comment (evenyag) [reply src/common/procedure-test/src/lib.rs:97]: What about execute_until_suspended_or_done?

Comment (waynexia) [reply src/common/procedure-test/src/lib.rs:97]: > What about execute_until_suspended_or_done?

I think you mean "poll".

Comment (evenyag) [reply src/common/procedure-test/src/lib.rs:97]: `poll` sounds like `execute once`.

**Review by fengjiachun — APPROVED** [review]
LGTM
