### PR TITLE
fix!: forbid to change information_schema

### LINKED ISSUE #3653: Readonly table error message should not be Internal Error
### What type of enhancement is this?

User experience

### What does the enhancement do?

```
mysql> SELECT * FROM build_info;
+---------------------+------------------------------------------+------------------+-----------+-------------+
| git_branch          | git_commit                               | git_commit_short | git_dirty | pkg_version |
+---------------------+------------------------------------------+------------------+-----------+-------------+
| checkpoint_checksum | 7e13a8edc970e5c3d383709dcbefda5f88c7fa77 | 7e13a8e          | false     | 0.7.1       |
+---------------------+------------------------------------------+------------------+-----------+-------------+
1 row in set (0.01 sec)

mysql> INSERT INTO build_info VALUES();
ERROR 1815 (HY000): Invalid SQL, error: column count mismatch, columns: 5, values: 0
mysql> INSERT INTO build_info VALUES('', '', '', '', '');
ERROR 1815 (HY000): Internal error: 1003
```

```
2024-04-07T14:27:24.166624Z ERROR on_query{protocol="mysql"}:mysql::do_query:do_query: frontend::instance: Failed to execute query: INSERT INTO build_info VALUES('', '', '', '', '') err=0: Table operation error, at src/frontend/src/instance.rs:272:14
1: Missing time index column, at src/operator/src/req_convert/insert.rs:39:10
2: Missing time index column in table: build_info, at src/operator/src/req_convert/insert.rs:36:10
```

We'd better to check readonly tables and return more friendly message.

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by CookiePieWw**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

close #3653

## What's changed and what's your intention?

As title. Following ops in `information_schema` are forbidden in this patch: 

- create, drop and truncate tables
- drop database
- insert into/delete from tables

Updated some sqlness tests for it.

## Checklist

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

## Summary by CodeRabbit

- **New Features**
  - Added checks to prevent modifications to read-only schemas and tables, specifically targeting the `information_schema`.
  
- **Bug Fixes**
  - Improved error handling to provide specific errors when attempting to modify read-only schemas and tables.
  
- **Refactor**
  - Enhanced schema and table operation checks to ensure compliance with read-only constraints.

### CODE REVIEW

File: src/operator/src/req_convert/insert/stmt_to_region.rs [hunk 1]
```diff
@@ -65,6 +65,11 @@ impl<'a> StatementToRegion<'a> {
         let table_schema = table.schema();
         let table_info = table.table_info();
 
+        ensure!(
+            schema != "information_schema",
```
Comment (killme2008) [inline src/operator/src/req_convert/insert/stmt_to_region.rs:69]: Use the constant `INFORMATION_SCHEMA_NAME`

https://github.com/GreptimeTeam/greptimedb/blob/ddc7a80f56885f70e935dd9831aabb9c68d17340/src/common/catalog/src/consts.rs#L16

Comment (killme2008) [inline src/operator/src/req_convert/insert/stmt_to_region.rs:69]: Use the constant `INFORMATION_SCHEMA_NAME`

https://github.com/GreptimeTeam/greptimedb/blob/ddc7a80f56885f70e935dd9831aabb9c68d17340/src/common/catalog/src/consts.rs#L16

File: src/query/src/datafusion.rs [hunk 2]
```diff
@@ -212,10 +218,19 @@ impl DatafusionQueryEngine {
         column_vectors: HashMap<String, VectorRef>,
         query_ctx: QueryContextRef,
     ) -> Result<Output> {
+        let catalog_name = table_name.catalog.to_string();
+        let schema_name = table_name.schema.to_string();
+        let table_name = table_name.table.to_string();
+
+        ensure!(
+            schema_name != "information_schema",
```
Comment (killme2008) [inline src/query/src/datafusion.rs:226]: Instead of this constant, I'd like to add a read-only schema test function in `catalog` crate, then we can check it by:

```
ensure!(!catalog::consts::is_readonly_schema(schema_name), TableReadOnlySnafu...);
```

If we add other read-only schemas, we can just change it in the `is_readonly_schema` function.

File: tests/cases/standalone/common/information_schema/tables.result [hunk 3]
```diff
@@ -44,3 +44,7 @@ drop schema abcde;
 
 Affected Rows: 0
 
+drop schema information_schema;
```
Comment (killme2008) [inline tests/cases/standalone/common/information_schema/tables.result:47]: Add tests to drop or alter a table in `information_schema`.

File: src/operator/src/error.rs [hunk 4]
```diff
@@ -718,6 +725,7 @@ impl ErrorExt for Error {
             | Error::SchemaNotFound { .. }
             | Error::SchemaExists { .. }
             | Error::SchemaInUse { .. }
+            | Error::SchemaReadOnly { .. }
```
Comment (killme2008) [inline src/operator/src/error.rs:728]: I think `Unsupported` status code is more proper.

**Comment by CookiePieWw** [comment]
Updated with a read-only check function, error code and some sqlness tests. PTAL @killme2008

I forgot to sync the clock before commit, so it may be a little strange that f336170bcdada6c332fddd3be2108728a9d473a6 is ahead of the comments QaQ.

File: src/catalog/src/consts.rs [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+//
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+use common_catalog::consts::INFORMATION_SCHEMA_NAME;
+
+pub fn is_readonly_schema(schema: &str) -> bool {
```
Comment (killme2008) [inline src/catalog/src/consts.rs:17]: I don't think we need a new module, you can put it into `common_catalog` directly.

File: src/operator/src/req_convert/insert/stmt_to_region.rs [hunk 6]
```diff
@@ -65,6 +65,11 @@ impl<'a> StatementToRegion<'a> {
         let table_schema = table.schema();
         let table_info = table.table_info();
 
+        ensure!(
+            !catalog::consts::is_readonly_schema(schema.as_str()),
```
Comment (killme2008) [inline src/operator/src/req_convert/insert/stmt_to_region.rs:69]: Prefer to use `&schema` instead of `schema.as_str()` in convention, other places as well.

**Review by killme2008 — COMMENTED** [review]
Almost done, thank you.

**Review by killme2008 — APPROVED** [review]
LGTM

**Review by sunng87 — APPROVED** [review]
This looks good for now. But eventually we need to implement this based on our permission system @MichaelScofield
