### PR TITLE
fix: unconditional statistics

### LINKED ISSUE #4692: Count with tag filter returns the unfiltered number of rows
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

```sql
drop table if exists count_where_bug;
create table count_where_bug (
    tag String,
    ts TimestampMillisecond time index,
    num Int64,
    primary key (tag),
) engine=mito with('append_mode'='true');

insert into count_where_bug (tag, ts, num)
values  ('a', '2024-09-06T06:00:01Z', 1),
        ('a', '2024-09-06T06:00:02Z', 2),
        ('a', '2024-09-06T06:00:03Z', 3),
        ('b', '2024-09-06T06:00:04Z', 4),
        ('b', '2024-09-06T06:00:05Z', 5);

select count(1) from count_where_bug where tag = 'b';
```

### What did you expect to see?

I expect to get 2 as result.

### What did you see instead?

But I am getting total number of rows - 5.

### What operating system did you use?

ArchLinux x64

### What version of GreptimeDB did you use?

0.9.2 from docker.io

### Relevant log output and stack trace

```bash
2024-09-06T13:32:32.355432Z  INFO LocalManager::submit_root_procedure: common_procedure::local::runner: Runner metasrv-procedure::DropTable-5e18069e-21d2-47ba-b186-257e7f20887e starts
2024-09-06T13:32:32.355587Z  INFO LocalManager::submit_root_procedure: common_meta::ddl::drop_table: Deleted table metadata for table 1083
2024-09-06T13:32:32.355732Z  INFO mito2::worker::handle_drop: Try to drop region: 4651449581568(1083, 0), worker: 3
2024-09-06T13:32:32.360541Z  INFO mito2::region: Stopped region manifest manager, region_id: 4651449581568(1083, 0)
2024-09-06T13:32:32.360602Z  INFO log_store::raft_engine::log_store: Namespace 4651449581568 obsoleted 1 entries, compacted index: 1, span: (None, None)
2024-09-06T13:32:32.360633Z  INFO mito2::worker::handle_drop: Region 4651449581568(1083, 0) is dropped logically, but some files are not deleted yet
2024-09-06T13:32:32.360678Z  INFO LocalManager::submit_root_procedure:RegionInvoker::handle_region_request:RegionServer::handle_region_request{region_id="4651449581568(1083, 0)"}:handle_request{request_type="Drop"}: datanode::region_server: Region 4651449581568(1083, 0) is deregistered from engine mito
2024-09-06T13:32:32.360808Z  INFO LocalManager::submit_root_procedure: common_procedure::local::runner: Procedure metasrv-procedure::DropTable-5e18069e-21d2-47ba-b186-257e7f20887e done
2024-09-06T13:32:32.360880Z  INFO LocalManager::submit_root_procedure: common_procedure::local::runner: Runner metasrv-procedure::DropTable-5e18069e-21d2-47ba-b186-257e7f20887e exits
2024-09-06T13:32:32.360912Z  INFO on_query{protocol="mysql"}:mysql::do_query:do_query:execute_stmt:drop_tables:DdlManager::submit_ddl_task: common_meta::ddl_manager: Table: 1083 is dropped via procedure_id ProcedureId(5e18069e-21d2-47ba-b186-257e7f20887e)
2024-09-06T13:32:32.361322Z  INFO LocalManager::submit_root_procedure: common_procedure::local::runner: Runner metasrv-procedure::CreateTable-965e4502-5989-4e82-901e-aa9cf6f10bf7 starts
2024-09-06T13:32:32.361584Z  INFO mito2::manifest::manager: Checkpoint not found in data/greptime/public/1084/1084_0000000000/manifest/, build manifest from scratch
2024-09-06T13:32:32.361664Z  INFO mito2::manifest::manager: Creating region manifest in data/greptime/public/1084/1084_0000000000/manifest/ with metadata RegionMetadata { column_metadatas: [[tag String null Tag 0], [ts TimestampMillisecond not null time_index metadata={"greptime:time_index": "true"} Timestamp 1], [num Int64 null Field 2]], time_index: 1, primary_key: [0], region_id: 4655744548864(1084, 0), schema_version: 0 }
2024-09-06T13:32:32.367128Z  INFO mito2::worker::handle_create: A new region created, worker: 0, region: RegionMetadata { column_metadatas: [[tag String null Tag 0], [ts TimestampMillisecond not null time_index metadata={"greptime:time_index": "true"} Timestamp 1], [num Int64 null Field 2]], time_index: 1, primary_key: [0], region_id: 4655744548864(1084, 0), schema_version: 0 }
2024-09-06T13:32:32.367195Z  INFO LocalManager::submit_root_procedure:RegionInvoker::handle_region_request:RegionServer::handle_region_request{region_id="4655744548864(1084, 0)"}:handle_request{request_type="Create"}: datanode::region_server: Region 4655744548864(1084, 0) is registered to engine mito
2024-09-06T13:32:32.367364Z  INFO LocalManager::submit_root_procedure: common_meta::ddl::create_table: Created table metadata for table 1084
2024-09-06T13:32:32.367389Z  INFO LocalManager::submit_root_procedure: common_procedure::local::runner: Procedure metasrv-procedure::CreateTable-965e4502-5989-4e82-901e-aa9cf6f10bf7 done
2024-09-06T13:32:32.367442Z  INFO LocalManager::submit_root_procedure: common_procedure::local::runner: Runner metasrv-procedure::CreateTable-965e4502-5989-4e82-901e-aa9cf6f10bf7 exits
2024-09-06T13:32:32.367479Z  INFO on_query{protocol="mysql"}:mysql::do_query:do_query:execute_stmt:create_table:create_table_inner:DdlManager::submit_ddl_task: common_meta::ddl_manager: Table: 1084 is created via procedure_id ProcedureId(965e4502-5989-4e82-901e-aa9cf6f10bf7)
2024-09-06T13:32:32.367497Z  INFO on_query{protocol="mysql"}:mysql::do_query:do_query:execute_stmt:create_table:create_table_inner: operator::statement::ddl: Successfully created table 'greptime.public.count_where_bug' with table id 1084
.
```

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

Closes #4692

## What's changed and what's your intention?

#4545 gives an incorrect impl of `statistics` method, which should consider both projection and filter of the underlying format reader when generating statistics.

## Checklist

- [x] I have written the necessary rustdoc comments.
- [x] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

### CODE REVIEW

File: src/mito2/src/read/scan_region.rs [hunk 1]
```diff
@@ -709,6 +709,10 @@ impl ScanInput {
         rows_in_files + rows_in_memtables
     }
 
+    pub(crate) fn predicate(&self) -> Option<Predicate> {
+        self.predicate.clone()
```
Comment (evenyag) [inline src/mito2/src/read/scan_region.rs:713]: Is predicate reference counted? Should we return a reference?

File: src/store-api/src/region_engine.rs [hunk 2]
```diff
@@ -367,6 +370,10 @@ impl RegionScanner for SinglePartitionScanner {
             ))
         })
     }
+
+    fn has_predicate(&self) -> bool {
+        false
```
Comment (evenyag) [inline src/store-api/src/region_engine.rs:375]: Can we ensure there is no predicate?

File: src/mito2/src/read/unordered_scan.rs [hunk 3]
```diff
@@ -228,6 +228,11 @@ impl RegionScanner for UnorderedScan {
 
         Ok(stream)
     }
+
+    fn has_predicate(&self) -> bool {
+        let predicate = self.stream_ctx.input.predicate();
```
Comment (evenyag) [inline src/mito2/src/read/unordered_scan.rs:233]: Does it contain the time predicate?

Comment (evenyag) [inline src/mito2/src/read/unordered_scan.rs:233]: Does it contain the time predicate?

File: tests/cases/standalone/common/aggregate/count.sql [hunk 4]
```diff
@@ -17,3 +17,21 @@ select count(*) from (select * from test cross join "HelloWorld");
...
+) engine=mito with('append_mode'='true');
+
+insert into count_where_bug (tag, ts, num)
+values  ('a', '2024-09-06T06:00:01Z', 1),
+        ('a', '2024-09-06T06:00:02Z', 2),
+        ('a', '2024-09-06T06:00:03Z', 3),
+        ('b', '2024-09-06T06:00:04Z', 4),
+        ('b', '2024-09-06T06:00:05Z', 5);
+
+select count(1) from count_where_bug where tag = 'b';
```
Comment (evenyag) [inline tests/cases/standalone/common/aggregate/count.sql:37]: Add cases that use ts or field filter if possible

File: src/mito2/src/read/scan_region.rs (hunk 1 above)
Comment (waynexia) [reply src/mito2/src/read/scan_region.rs:713]: it is

File: src/store-api/src/region_engine.rs (hunk 2 above)
Comment (waynexia) [reply src/store-api/src/region_engine.rs:375]: from the constructor, i think so

File: src/mito2/src/read/unordered_scan.rs (hunk 3 above)
Comment (waynexia) [reply src/mito2/src/read/unordered_scan.rs:233]: It's derived from filters in scan request directly.

Comment (waynexia) [reply src/mito2/src/read/unordered_scan.rs:233]: ditto

Comment (evenyag) [reply src/mito2/src/read/unordered_scan.rs:233]: We removes the time filter from the request so it may be empty if there is only a filter for the timestamp

**Review by evenyag — APPROVED** [review]

**Review by v0y4g3r — COMMENTED** [review]
LGTM

**Review by v0y4g3r — APPROVED** [review]
