### PR TITLE
fix: allow ipv4_num_to_string to accept valid integers

### LINKED ISSUE #7977: Make ipv4_num_to_string function accepts int32
```sql
mysql> select ipv4_num_to_string(3232235521::uint32);
+------------------------------------------------------------------+
| ipv4_num_to_string(arrow_cast(Int64(3232235521),Utf8("UInt32"))) |
+------------------------------------------------------------------+
| 192.168.0.1                                                      |
+------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> select ipv4_num_to_string(3232235521);
ERROR 1815 (HY000): (PlanQuery): Failed to plan SQL: Error during planning: Failed to coerce arguments for 'ipv4_num_to_string': cannot coerce Int64 to Exact([UInt32]). No matching function for 'ipv4_num_to_string(Int64)'. You may need an explicit cast.
    Candidate functions:
    ipv4_num_to_string(UInt32)
```

We could update the `ipv4_num_to_string` signature to accept `Int32` and automatically coerce the input type.

https://github.com/GreptimeTeam/greptimedb/blob/8a3bd374a89a74fc2dff9ef24d55a71b30c4e1f0/src/common/function/src/scalars/ip/ipv4.rs#L47

### PR DESCRIPTION
**Pull request by JoeS51**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

Closes [issue 7977](https://github.com/GreptimeTeam/greptimedb/issues/7977)

## What's changed and what's your intention?

Previously, the `ipv4_num_to_string` function would reject any integers that were not of type `uint32` even if the passed in integer could be casted into a valid `uint32`. This PR broadens the `ipv4_num_to_string` signature to take in any of `UInt32`, `UInt64`, `Int32`, or `Int64, and then strictly casts the input to `UInt32` before formatting it as an IPv4 string.

This removes the need for explicit `::uint32` casts for valid integers while still rejecting invalid values, such as negative numbers or integers larger than `UInt32::MAX`. This PR also has unit tests and a sqlness regression test for the `Int64` case reported in the issue.

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [x] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [x] API changes are backward compatible.
- [x] Schema or data changes are backward compatible.

### CODE REVIEW

**Review by killme2008 — APPROVED** [review]
LGTM

Thanks

File: src/common/function/src/scalars/ip/ipv4.rs [hunk 1]
```diff
@@ -43,8 +43,13 @@ pub struct Ipv4NumToString {
...
         Self {
-            signature: Signature::new(
-                TypeSignature::Exact(vec![DataType::UInt32]),
+            signature: Signature::one_of(
+                vec![
+                    TypeSignature::Exact(vec![DataType::UInt32]),
+                    TypeSignature::Exact(vec![DataType::UInt64]),
+                    TypeSignature::Exact(vec![DataType::Int32]),
+                    TypeSignature::Exact(vec![DataType::Int64]),
+                ],
```
Comment (fengjiachun) [inline src/common/function/src/scalars/ip/ipv4.rs]: Could we make this signature coercible over the integer family instead of enumerating four exact types?

This fixes the `Int64` literal case, but it looks like other valid integer inputs such as `SMALLINT`, `TINYINT`, `UInt8`, and `UInt16` would still be rejected during signature matching. Since the implementation already casts to `UInt32` at runtime, a coercible integer signature seems closer to the intended behavior here.

Comment (JoeS51) [reply src/common/function/src/scalars/ip/ipv4.rs]: Hi @fengjiachun, thank you for pointing out this cleaner solution! I've changed the signature to use a coercible `TypeSignatureClass::Integer` instead of using exact integer types. I ran the tests and verified locally that inputs such as `TINYINT` and `UInt8` are now accepted by this function.

Let me know if this looks good to you.

**Review by fengjiachun — APPROVED** [review]
LGTM
