### PR TITLE
fix: open region missing options

### LINKED ISSUE #2472: Lost table options when opening regions
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

When opening a region, the options passed into `RegionOpenRequest ` is always empty:

https://github.com/GreptimeTeam/greptimedb/blob/9d0de25bff1b82582a10ada05d06fce9b09918a0/src/datanode/src/heartbeat/handler.rs#L57

Then the opened region lost the region options, and the `TTL` and compaction behavior didn't respect the table options.

### What operating system did you use?

All system

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

.

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Fix open region missing options

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
fix #2472

### CODE REVIEW

File: src/datanode/src/datanode.rs [hunk 1]
```diff
@@ -277,39 +278,45 @@ impl DatanodeBuilder {
...
-        while let Some(table_value) = table_values.next().await {
-            let table_value = table_value.context(GetMetadataSnafu)?;
-            for region_number in table_value.regions {
-                regions.push((
-                    RegionId::new(table_value.table_id, region_number),
-                    table_value.engine.clone(),
-                    table_value.region_storage_path.clone(),
-                ));
+        let mut stream = Box::pin(try_stream! {
+            while let Some(table_value) = table_values.try_next().await.context(GetMetadataSnafu)? {
```
Comment (fengjiachun) [inline src/datanode/src/datanode.rs:286]: This will be very slow because it requires looping calls to the `table_info_manager` by table_id.
I think we should add the region `options`  to `TableDataValue` to avoid calling `table_info_manager` in the loop.

File: src/common/meta/src/key/datanode_table.rs [hunk 2]
```diff
@@ -197,18 +208,19 @@ impl DatanodeTableManager {
                 opts.push(TxnOp::Delete(raw_key))
             }
         }
-
+        let need_update_options = current_region_options != new_region_options;
```
Comment (fengjiachun) [inline src/common/meta/src/key/datanode_table.rs:211]: `current_region_options` is useless, regardless of whether `current` is equal to `new`, it is actually using the `new`.

**Comment by killme2008** [comment]
@fengjiachun @MichaelScofield Please take a look

**Review by killme2008 — COMMENTED** [review]
Can we add a test case to ensure that the region opitons is correct after restarting?

File: src/common/meta/src/key.rs [hunk 3]
```diff
@@ -446,10 +449,14 @@ impl TableMetadataManager {
     pub async fn update_table_route(
         &self,
         table_id: TableId,
-        engine: &str,
-        region_storage_path: &str,
+        UpdateDatanodeTableContext {
+            engine,
+            region_storage_path,
+            region_options: current_region_options,
+        }: UpdateDatanodeTableContext<'_>,
```
Comment (fengjiachun) [inline src/common/meta/src/key.rs:456]: updata_ctx:  UpdateDatanodeTableContext<'_>,

File: src/common/meta/src/key.rs [hunk 4]
```diff
@@ -458,10 +465,14 @@ impl TableMetadataManager {
 
         let update_datanode_table_txn = self.datanode_table_manager().build_update_txn(
             table_id,
-            engine,
-            region_storage_path,
+            UpdateDatanodeTableContext {
+                engine,
+                region_storage_path,
+                region_options: current_region_options,
+            },
```
Comment (fengjiachun) [inline src/common/meta/src/key.rs:472]: updata_ctx

File: src/common/meta/src/key/datanode_table.rs [hunk 5]
```diff
@@ -197,18 +213,19 @@ impl DatanodeTableManager {
...
         for (datanode, regions) in new_region_distribution.into_iter() {
```
Comment (fengjiachun) [inline src/common/meta/src/key/datanode_table.rs:217]:
```
            let update_needed =
                if let Some(current_region) = current_region_distribution.get(&datanode) {
                    // Updates if need.
                    *current_region != regions || current_region_options != new_region_options
                } else {
                    true
                };
            if update_needed {
                let key = DatanodeTableKey::new(datanode, table_id);
                let raw_key = key.as_raw_key();
                let val = DatanodeTableValue::new(
                    table_id,
                    regions,
                    engine.to_string(),
                    region_storage_path.to_string(),
                    new_region_options.clone(),
                )
                .try_as_raw_value()?;
                opts.push(TxnOp::Put(raw_key, val));
            }
```

**Review by fengjiachun — APPROVED** [review]

**Comment by killme2008** [comment]
@WenyXu  I am afraid that the added sqlness test can not cover this case because the `show create table` retrieves the table metadata from metasrv directly, but in this issue is that the opened region can't get the correct table options when it's opened on runtime, we have to assert the runtime region options is correct after restarting.

**Comment by WenyXu** [comment]
> @WenyXu I am afraid that the added sqlness test can not cover this case because the `show create table` retrieves the table metadata from metasrv directly, but in this issue is that the opened region can't get the correct table options when it's opened on runtime, we have to assert the runtime region options is correct after restarting.

Oops, I see. Let me add an Integration test later.

File: src/common/meta/src/key/datanode_table.rs [hunk 6]
```diff
@@ -32,6 +33,11 @@ use crate::rpc::store::RangeRequest;
 use crate::rpc::KeyValue;
 use crate::DatanodeId;
 
+pub struct UpdateDatanodeTableContext<'a> {
+    pub engine: &'a str,
+    pub region_storage_path: &'a str,
+    pub region_options: &'a HashMap<String, String>,
+}
```
Comment (fengjiachun) [inline src/common/meta/src/key/datanode_table.rs:40]: Add an empty line

**Review by fengjiachun — APPROVED** [review]

File: src/common/meta/src/key/datanode_table.rs [hunk 7]
```diff
@@ -89,6 +96,8 @@ pub struct DatanodeTableValue {
     pub engine: String,
     #[serde(default)]
     pub region_storage_path: String,
+    #[serde(default)]
+    pub region_options: HashMap<String, String>,
```
Comment (MichaelScofield) [inline src/common/meta/src/key/datanode_table.rs:100]: I don't think `region_options`(as well as `engine` and `region_storage_path`) is best placed in `DatanodeTableValue`. These region attributes has little to do with the placement of regions among Datanode, which is the intention of `DatanodeTableValue` in the first place. 

It looks to me that doing so is trying to give us the direct convenience when figuring out the regions to open in Datanode. That's fine. But I think a more proper way to do it is "indirect": move these region attributes into a region id indexed `RegionInfoValue`. That might introduce extra efforts when opening the regions, but gain more flexibility, and less counterintuitive.

Comment (WenyXu) [reply src/common/meta/src/key/datanode_table.rs:100]: The key problem is to reduce requests sent to etcd.

**Comment by fengjiachun** [comment]
@killme2008 PTAL

File: src/common/meta/src/key/datanode_table.rs (hunk 7 above)
Comment (killme2008) [reply src/common/meta/src/key/datanode_table.rs:100]: @WenyXu @MichaelScofield Have we reached an agreement here?

**Comment by WenyXu** [comment]
@killme2008 @fengjiachun @MichaelScofield PTAL

**Review by fengjiachun — APPROVED** [review]
LGTM

**Review by killme2008 — APPROVED** [review]
