### PR TITLE
fix: duplicate information_schema

### LINKED ISSUE #2976: Duplicate information_schema
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode, Frontend, Datanode

### Minimal reproduce step

```sql
MySQL [(none)]> show schemas;
+--------------------+
| Schemas            |
+--------------------+
| information_schema |
| public             |
+--------------------+
2 rows in set (0.002 sec)

MySQL [(none)]> create schema information_schema;
Query OK, 1 row affected (0.000 sec)

MySQL [(none)]> show schemas;
+--------------------+
| Schemas            |
+--------------------+
| information_schema |
| information_schema |
| public             |
+--------------------+
3 rows in set (0.000 sec)
```

@Taylor-lagrange found this in https://github.com/GreptimeTeam/greptimedb/pull/2928#discussion_r1433609401

### What did you expect to see?

Cannot create a schema named `information_schema` since there is one

### What did you see instead?

two duplicate `information_schema`s

### What operating system did you use?

Doesn't matter

### Relevant log output and stack trace

_No response_

### PR DESCRIPTION
**Pull request by killme2008**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Fixed #2976 

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

File: src/catalog/src/memory/manager.rs [hunk 1]
```diff
@@ -143,6 +143,13 @@ impl MemoryCatalogManager {
                 schema: DEFAULT_PRIVATE_SCHEMA_NAME.to_string(),
             })
             .unwrap();
+        manager
+            .register_schema_sync(RegisterSchemaRequest {
+                catalog: DEFAULT_CATALOG_NAME.to_string(),
+
```
Comment (sunng87) [inline src/catalog/src/memory/manager.rs:149]: remove emply line

**Review by sunng87 — APPROVED** [review]

File: tests/cases/standalone/common/system/information_schema.sql [hunk 2]
```diff
@@ -1,4 +1,6 @@
 -- scripts table has different table ids in different modes
```
Comment (waynexia) [inline tests/cases/standalone/common/system/information_schema.sql:1]: This comment seems belongs to the next `SELECT` clause

**Review by waynexia — APPROVED** [review]
LGTM
