### PR TITLE
fix: convert JSON type to JSON string in COPY TABLE TO statment

### LINKED ISSUE #6240: COPY TABLE does not correctly export JSON format
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Other

### Minimal reproduce step

1.  Create table
```sql
CREATE TABLE jsons (j JSON, t timestamp time index);
```

2. Insert data
```sql
INSERT INTO jsons VALUES('[null]', 0),
('[true]', 1),
('[false]', 2);
```
3. Copy table to fs

```
COPY jsons TO '/tmp/export/demo.csv' WITH (format='csv');
```

### What did you expect to see?

All JSON values should be exported as JSON strings, like this:
```bash
cat /tmp/export/demo.csv
j,t
"[null]",1970-01-01T00:00:00
"[true]",1970-01-01T00:00:00.001
"[false]",1970-01-01T00:00:00.002
```

### What did you see instead?

```bash
cat /tmp/export/demo.csv
j,t
8000000100000000,1970-01-01T00:00:00
8000000140000000,1970-01-01T00:00:00.001
8000000130000000,1970-01-01T00:00:00.002
```

### What operating system did you use?

doesn't matter

### What version of GreptimeDB did you use?

doesn't matter

### Relevant log output and stack trace

```bash

```

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

fixes #6240
## What's changed and what's your intention?

This PR fixes the JSON type export in COPY TABLE TO statement. Previously, it directly output the internal representation of JSON type, now it correctly converts JSON type to JSON string format.

#### Changes
- Add `SendableRecordBatchMapper` to handle type conversion in `RecordBatch` stream
- Implement JSON type to JSON string conversion logic
- Updated test cases to verify JSON type export functionality

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

File: tests/cases/standalone/common/copy/copy_from_fs_csv.sql [hunk 1]
```diff
@@ -15,6 +19,18 @@ Copy with_filename FROM '${SQLNESS_HOME}/demo/export/csv/demo.csv' with (format=
 
 select * from with_filename order by ts;
 
+CREATE TABLE with_json(host string, cpu double, memory double, jsons JSON, ts timestamp time index);
+
+Copy with_json FROM '${SQLNESS_HOME}/demo/export/json/demo.json' with (format='json');
+
+select host, cpu, memory, json_to_string(jsons), ts from with_json order by ts;
```
Comment (fengjiachun) [inline tests/cases/standalone/common/copy/copy_from_fs_csv.sql:26]:
```suggestion
SELECT host, cpu, memory, json_to_string(jsons), ts FROM with_json order by ts;
```

File: src/common/recordbatch/src/lib.rs [hunk 2]
```diff
@@ -58,6 +61,142 @@ pub struct OrderOption {
...
+    for (vector, schema) in batch.columns.iter().zip(original_schema.column_schemas()) {
+        if let ConcreteDataType::Json(j) = schema.data_type {
+            let mut string_vector_builder = StringVectorBuilder::with_capacity(vector.len());
+            for i in 0..vector.len() {
+                let value = vector.get(i);
+                if value.is_null() {
+                    string_vector_builder.push(None);
+                } else {
+                    let string_value = json_type_value_to_string(
+                        // Safety: value is must be a binary value.
```
Comment (killme2008) [inline src/common/recordbatch/src/lib.rs]:
```suggestion
                        // Safety: value must be a binary value.
```

File: src/common/recordbatch/src/lib.rs [hunk 3]
```diff
@@ -58,6 +61,142 @@ pub struct OrderOption {
...
+pub fn map_json_type_to_string(
+    batch: RecordBatch,
+    original_schema: &SchemaRef,
+    mapped_schema: &SchemaRef,
+) -> Result<RecordBatch> {
+    let mut vectors = Vec::with_capacity(original_schema.column_schemas().len());
+    for (vector, schema) in batch.columns.iter().zip(original_schema.column_schemas()) {
+        if let ConcreteDataType::Json(j) = schema.data_type {
+            let mut string_vector_builder = StringVectorBuilder::with_capacity(vector.len());
+            for i in 0..vector.len() {
```
Comment (killme2008) [inline src/common/recordbatch/src/lib.rs]: I think it's better to use `iter_data` to iterate the vector:

https://greptimedb.rs/datatypes/vectors/struct.BinaryVector.html#method.get_data

We can downcast the vector into `BinaryVector`.

File: src/common/recordbatch/src/lib.rs (hunk 2 above)
Comment (WenyXu) [reply src/common/recordbatch/src/lib.rs]: resolved in [4b29189](https://github.com/GreptimeTeam/greptimedb/pull/6255/commits/4b29189786d3ad9f9f446bc89366d0648f2c0c53)

File: src/common/recordbatch/src/lib.rs (hunk 3 above)
Comment (WenyXu) [reply src/common/recordbatch/src/lib.rs]: resolved in [4b29189](https://github.com/GreptimeTeam/greptimedb/pull/6255/commits/4b29189786d3ad9f9f446bc89366d0648f2c0c53)

Comment (killme2008) [reply src/common/recordbatch/src/lib.rs]: Why not use `iter_data` instead of for loop?

Comment (WenyXu) [reply src/common/recordbatch/src/lib.rs]: Oh, I see. resolved in [d4c1e79](https://github.com/GreptimeTeam/greptimedb/pull/6255/commits/d4c1e79da311a97ba0bd52864d3d308d8c332754)

**Review by killme2008 — APPROVED** [review]
LGTM
