### PR TITLE
fix: skip schema check to avoid schema mismatch brought by metadata

### LINKED ISSUE #5659: 0.12 doesn't support GROUP BY in CTE query
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Query Engine

### Minimal reproduce step

```sql
CREATE TABLE grpc_latencies (
    ts TIMESTAMP TIME INDEX,
    host VARCHAR(255),
    latency FLOAT,
    PRIMARY KEY(host),
);

INSERT INTO grpc_latencies VALUES 
('2023-10-01 10:00:00', 'host1', 120),
('2023-10-01 10:00:00', 'host2', 150),
('2023-10-01 10:00:05', 'host1', 130);


WITH
latencies AS (
  SELECT
    ts,
    host,
    AVG(latency) RANGE '2s' AS avg_latency
  FROM grpc_latencies 
  ALIGN '2s' BY (host) FILL PREV
)
SELECT
  latencies.ts, 
  AVG(latencies.avg_latency)
FROM latencies
GROUP BY latencies.ts
```

### What did you expect to see?

in 0.11.3, the result is:

ts | AVG(latencies.avg_latency)
-- | --
1696114800000 | 135
1696114802000 | 120
1696114804000 | 130

### What did you see instead?

```
{
    "code": 3001,
    "error": "DataFusion error: Internal error: Physical input schema should be the same as the one converted from logical input schema. Differences: .\nThis was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker",
    "execution_time_ms": 2
}
```

### What operating system did you use?

doesn't matter

### What version of GreptimeDB did you use?

0.12.0

### Relevant log output and stack trace

```bash
greptime_12-1  | 2025-03-06T12:07:47.848868Z ERROR sql{protocol="http" request_type="sql"}:do_query: frontend::instance: Failed to execute query: WITH latencies AS (SELECT ts, host, range_fn(AVG(latency), '2s', 'PREV', '1', host, '2s', '') AS avg_latency FROM grpc_latencies GROUP BY host, ts) SELECT latencies.ts, AVG(latencies.avg_latency) FROM latencies GROUP BY latencies.ts err=0: Table operation error, at src/frontend/src/instance.rs:280:16
greptime_12-1  | 1: Failed to execute logical plan, at /greptimedb/src/operator/src/statement.rs:460:14
greptime_12-1  | 2: Failure during query execution, at src/query/src/datafusion.rs:315:14
greptime_12-1  | 3: DataFusion error, at src/query/src/datafusion.rs:313:14
greptime_12-1  | 4: Internal("Physical input schema should be the same as the one converted from logical input schema. Differences: ")
greptime_12-1  | 2025-03-06T12:07:47.848977Z ERROR sql{protocol="http" request_type="sql"}: servers::http::result::error_result: Failed to handle HTTP request err=0: Failed to execute query, at /greptimedb/src/servers/src/query_handler/sql.rs:87:49
greptime_12-1  | 1: Table operation error, at src/frontend/src/instance.rs:280:16
greptime_12-1  | 2: Failed to execute logical plan, at /greptimedb/src/operator/src/statement.rs:460:14
greptime_12-1  | 3: Failure during query execution, at src/query/src/datafusion.rs:315:14
greptime_12-1  | 4: DataFusion error, at src/query/src/datafusion.rs:313:14
greptime_12-1  | 5: Internal("Physical input schema should be the same as the one converted from logical input schema. Differences: ")
```

### PR DESCRIPTION
**Pull request by v0y4g3r**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
- fixes #5659
## What's changed and what's your intention?

Skip schema check in aggr to avoid schema mismatch caused by metadata.

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [x] API changes are backward compatible.
- [x] Schema or data changes are backward compatible.

### CODE REVIEW

**Comment by yihong0618** [comment]
maybe add sqlness for this?

**Review by killme2008 — APPROVED** [review]
LGTM

It's better to move the test into cases/standalone/common/cte/

File: tests/cases/standalone/common/range/cte.sql [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+                          host,
+                          AVG(latency) RANGE '2s' AS avg_latency
+                   FROM grpc_latencies ALIGN '2s' BY (host) FILL PREV
+    )
+SELECT latencies.ts,
+       AVG(latencies.avg_latency)
+FROM latencies
+GROUP BY latencies.ts ORDER BY latencies.ts;
+
+DROP TABLE grpc_latencies;
```
Comment (killme2008) [inline tests/cases/standalone/common/range/cte.sql:25]: Needs a blank line and move the test into cases/standalone/common/cte/

**Review by waynexia — APPROVED** [review]
