### PR TITLE
fix: abort parquet writer 

### LINKED ISSUE #1786: `BufferedWriter::close` returns wrong file size
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Datanode

### What happened?

`BufferedWriter::close` returns the bytes flushed during last flush attempt when closing writer instead of the size of whole file.

https://github.com/GreptimeTeam/greptimedb/blob/bf3562090448adb8bcc42247cb70f045f52f71ff/src/common/datasource/src/buffered_writer.rs#L56-L59

### What operating system did you use?

NA

### Relevant log output and stack trace

```bash
NA
```

### How can we reproduce the bug?

```rs
    #[tokio::test]
    async fn test_write_large_data() {
        common_telemetry::init_default_ut_logging();
        let schema = memtable_tests::schema_for_test();
        let memtable = DefaultMemtableBuilder::default().build(schema);

        let mut rows_written = 0;
        for i in 0..16 {
            let range: Range<i64> = i * 1024..(i + 1) * 1024;
            let keys = range.clone().collect::<Vec<_>>();
            let values = range
                .map(|idx| (Some(idx as u64), Some(idx as u64)))
                .collect::<Vec<_>>();
            memtable_tests::write_kvs(&*memtable, i as u64, OpType::Put, &keys, &values);
            rows_written += keys.len();
        }

        let dir = create_temp_dir("write_parquet");
        let path = dir.path().to_str().unwrap();

        let object_store = create_object_store(path);
        let sst_file_name = "test-flush.parquet";
        let iter = memtable.iter(IterContext::default()).unwrap();
        let writer = ParquetWriter::new(sst_file_name, Source::Iter(iter), object_store.clone());

        let sst_info = writer
            .write_sst(&sst::WriteOptions {
                sst_write_buffer_size: ReadableSize::kb(4),
            })
            .await
            .unwrap()
            .unwrap();
        let file_meta = object_store.stat(sst_file_name).await.unwrap();
        assert!(file_meta.is_file());
        assert_eq!(sst_info.file_size, file_meta.content_length());
        assert_eq!(rows_written, sst_info.num_rows);
    }
```

### PR DESCRIPTION
**Pull request by v0y4g3r**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

This PR fixes two issues:
- `ParquetWriter::close` returns the bytes during last flush attempt when closing underlying writer instead of the size of whole file: https://github.com/GreptimeTeam/greptimedb/pull/1785/files#diff-051f815e4fa71f86735dd28136c0d475fa75dceb4903a7ab47c93b60576ad970L56
- [`stream_to_file`](https://github.com/GreptimeTeam/greptimedb/pull/1785/files#diff-423117cc93ea8a8d6deed211495ad49b92650c130e6932d1d9282c4eff8b52c9L184-L188) and [`BufferedWriter::try_new`](https://github.com/GreptimeTeam/greptimedb/pull/1785/files#diff-23b04e5dea6eef5d5101622d0d8d2046da2f0331c97474c484cc647ddaf6f4dfL50-L53) eagerly create underlying files even if there's no row has been written. This PR tries to fix this issue by lazily creating files upon first flush.

## Checklist

- [X]  I have written the necessary rustdoc comments.
- [X]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
Fixes #1786 and  #1787

### CODE REVIEW

File: src/common/datasource/src/buffered_writer.rs [hunk 1]
```diff
@@ -42,58 +44,76 @@ pub trait ArrowWriterCloser {
...
 
-impl<T: AsyncWrite + Send + Unpin, U: DfRecordBatchEncoder> BufferedWriter<T, U> {
+impl<
+        T: AsyncWrite + Send + Unpin,
+        U: DfRecordBatchEncoder,
+        F: FnMut(String) -> Fut,
+        Fut: Future<Output = Result<T>>,
+    > LazyBufferedWriter<T, U, F>
+{
     pub async fn close(&mut self) -> Result<()> {
```
Comment (WenyXu) [inline src/common/datasource/src/buffered_writer.rs:80]: nit: Regarding the different behavior between the two `close` methods, adding some comments is better.
``` suggestion
    /// Closes the writer without flushing the buffer data.
    pub async fn close(&mut self) -> Result<()> {
```

**Review by WenyXu — APPROVED** [review]
I feel like I'll be jailed for making bugs 🥲

File: src/storage/src/sst/parquet.rs [hunk 2]
```diff
@@ -132,13 +132,15 @@ impl<'a> ParquetWriter<'a> {
         }
 
         if rows_written == 0 {
+            info!("No data written, try abort writer");
```
Comment (killme2008) [inline src/storage/src/sst/parquet.rs:135]: Add the file path to the log.

File: src/storage/src/sst/parquet.rs [hunk 3]
```diff
@@ -132,13 +132,15 @@ impl<'a> ParquetWriter<'a> {
...
             // if the source does not contain any batch, we skip writing an empty parquet file.
-            if !buffered_writer.abort().await {
-                warn!(
-                    "Partial file {} has been uploaded to remote storage",
-                    self.file_path
-                );
-            }
+            // if !buffered_writer.abort().await {
```
Comment (killme2008) [inline src/storage/src/sst/parquet.rs:137]: Remove the commented code.

**Review by killme2008 — APPROVED** [review]
A few suggestions. LGTM.

File: src/common/datasource/src/buffered_writer.rs (hunk 1 above)
Comment (v0y4g3r) [reply src/common/datasource/src/buffered_writer.rs:80]: > // Closes the writer without flushing the buffer data.

Maybe it should be renamed to `close_inner_writer`

**Comment by v0y4g3r** [comment]
@killme2008 @WenyXu PTAL
