### PR TITLE
fix: use number of partitions as parallilism in region scanner 

### LINKED ISSUE #4668: Query timestamp in append mode yields incorrect result
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

1. Create table with append mode:
```sql
create table t (
    ts timestamp time index,
    host string primary key,
    not_pk string,
    val double,
) with (append_mode='true', 'compaction.type'='twcs','compaction.twcs.max_active_window_files'='8','compaction.twcs.max_inactive_window_files'='8');
```

2. Insert 9 rows and flush
```sql
insert into t values
    (0, 'a', '🌕', 1.0),
    (1, 'b', '🌖', 2.0),
    (1, 'a', '🌗', 3.0),
    (1, 'c', '🌘', 4.0),
    (2, 'a', '🌑', 5.0),
    (2, 'b', '🌒', 6.0),
    (2, 'a', '🌓', 7.0),
    (3, 'c', '🌔', 8.0),
    (3, 'd', '🌕', 9.0);

admin flush_table('t');    
```

3. Insert another 9 rows and flush
```sql
insert into t values
    (10, 'a', '🌕', 1.0),
    (11, 'b', '🌖', 2.0),
    (11, 'a', '🌗', 3.0),
    (11, 'c', '🌘', 4.0),
    (12, 'a', '🌑', 5.0),
    (12, 'b', '🌒', 6.0),
    (12, 'a', '🌓', 7.0),
    (13, 'c', '🌔', 8.0),
    (13, 'd', '🌕', 9.0);
admin flush_table('t');    
```

4. Then select num of total rows and all timestamps
```sql
select count(ts) from t;    

select ts from t;
```

### What did you expect to see?

- `select count(ts) from t` should give 18 since 18 rows are written
```
+-------------+
| COUNT(t.ts) |
+-------------+
| 18          |
+-------------+
```
- `select ts from t` should list all inserted timestamps
```
+-------------------------+
| ts                      |
+-------------------------+
| 1970-01-01T00:00:00     |
| 1970-01-01T00:00:00.001 |
| 1970-01-01T00:00:00.002 |
| 1970-01-01T00:00:00.002 |
| 1970-01-01T00:00:00.010 |
| 1970-01-01T00:00:00.011 |
| 1970-01-01T00:00:00.012 |
| 1970-01-01T00:00:00.012 |
| 1970-01-01T00:00:00.001 |
| 1970-01-01T00:00:00.002 |
| 1970-01-01T00:00:00.011 |
| 1970-01-01T00:00:00.012 |
| 1970-01-01T00:00:00.001 |
| 1970-01-01T00:00:00.003 |
| 1970-01-01T00:00:00.011 |
| 1970-01-01T00:00:00.013 |
| 1970-01-01T00:00:00.003 |
| 1970-01-01T00:00:00.013 |
+-------------------------+
```

### What did you see instead?

- `select count(ts) from t` gives 18:
```
+-------------+
| COUNT(t.ts) |
+-------------+
| 18          |
+-------------+
```
- But `select ts from t` only returns 9 rows:
```
+----------------------------+
| ts                         |
+----------------------------+
| 1970-01-01 00:00:00.010000 |
| 1970-01-01 00:00:00.011000 |
| 1970-01-01 00:00:00.012000 |
| 1970-01-01 00:00:00.012000 |
| 1970-01-01 00:00:00.011000 |
| 1970-01-01 00:00:00.012000 |
| 1970-01-01 00:00:00.011000 |
| 1970-01-01 00:00:00.013000 |
| 1970-01-01 00:00:00.013000 |
+----------------------------+
9 rows in set (0.07 sec)

```

### What operating system did you use?

NA

### What version of GreptimeDB did you use?

0.9.2

### Relevant log output and stack trace

_No response_

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

🥵 Closes #4668

## Checklist

- [x] I have written the necessary rustdoc comments.
- [x] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

### CODE REVIEW

File: tests/cases/standalone/common/select/flush_append_only.sql [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+    (12, 'a', '🌓', 7.0),
+    (13, 'c', '🌔', 8.0),
+    (13, 'd', '🌕', 9.0);
+
+admin flush_table ('t');
+
+select
+    count(ts)
+from
+    t;
```
Comment (v0y4g3r) [inline tests/cases/standalone/common/select/flush_append_only.sql:49]: order by ts

**Review by evenyag — APPROVED** [review]
