### PR TITLE
fix(mito): avoid caching empty batches in row group

### LINKED ISSUE #4650: Last point reports empty result set
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode, Storage Engine

### Minimal reproduce step

1. Write test data using TSBS cpu metric data set.
2. Flush table using `ADMIN flush_table('cpu')`
3. Query last point of every time series using:
```sql
SELECT   
  last_value(hostname order by ts),   
  last_value(region order by ts),   
  last_value(datacenter order by ts),   
  last_value(rack order by ts),   
  last_value(os order by ts),   
  last_value(arch order by ts),   
  last_value(team order by ts),   
  last_value(service order by ts),   
  last_value(service_version order by ts),   
  last_value(service_environment order by ts),   
  last_value(usage_user order by ts),   
  last_value(usage_system order by ts),   
  last_value(usage_idle order by ts),   
  last_value(usage_nice order by ts),   
  last_value(usage_iowait order by ts),   
  last_value(usage_irq order by ts),   
  last_value(usage_softirq order by ts),   
  last_value(usage_steal order by ts),   
  last_value(usage_guest order by ts),   
  last_value(usage_guest_nice order by ts) 
FROM cpu group by hostname;
```
This step is expected to get 4000 rows of results in that the data set has 4000 time series in total.
4. Repeat the query again. Now you will get empty set, which is inccorect
image
 

### What did you expect to see?

The query above should always give a result of 4000 rows.

### What did you see instead?

An empty set.

### What operating system did you use?

NA

### What version of GreptimeDB did you use?

0.9.2

### Relevant log output and stack trace

_No response_

### PR DESCRIPTION
**Pull request by v0y4g3r**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

- fixes #4650

## Performance regression

Run the same TSBS query with `region_engine.mito.selector_result_cache_size=2GB`:

Before:
```
$ ./bin/tsbs_run_queries_influx --file=./bench-data/greptime-queries-lastpoint.dat     --db-name=benchmark     --urls="http://localhost:4000"
Run complete after 10 queries with 1 workers (Overall query rate 2.61 queries/sec):
Influx last row per host:
min:    14.68ms, med:    28.02ms, mean:   383.09ms, max: 3610.37ms, stddev:  1075.75ms, sum:   3.8sec, count: 10
all queries             :
min:    14.68ms, med:    28.02ms, mean:   383.09ms, max: 3610.37ms, stddev:  1075.75ms, sum:   3.8sec, count: 10
wall clock time: 3.870371sec
```

After:

```
$ ./bin/tsbs_run_queries_influx --file=./bench-data/greptime-queries-lastpoint.dat     --db-name=benchmark     --urls="http://localhost:4000"
Run complete after 10 queries with 1 workers (Overall query rate 2.89 queries/sec):
Influx last row per host:
min:   307.68ms, med:   334.83ms, mean:   345.94ms, max:  425.07ms, stddev:    31.58ms, sum:   3.5sec, count: 10
all queries             :
min:   307.68ms, med:   334.83ms, mean:   345.94ms, max:  425.07ms, stddev:    31.58ms, sum:   3.5sec, count: 10
wall clock time: 3.473471sec
```

Within noise threshold.

## Checklist

- [x] I have written the necessary rustdoc comments.
- [x] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

### CODE REVIEW

File: tests/cases/standalone/common/select/last_value.sql [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+-- repeat the query again, ref: https://github.com/GreptimeTeam/greptimedb/issues/4650
+select
+        last_value(host order by ts),
+        last_value(not_pk order by ts),
+        last_value(val order by ts)
+from t
+    group by host
+    order by host;
+
+drop table t;
```
Comment (v0y4g3r) [inline tests/cases/standalone/common/select/last_value.sql:38]:
```suggestion
drop table t;

```

**Review by waynexia — APPROVED** [review]

**Review by fengjiachun — APPROVED** [review]
LGTM
