### PR TITLE
fix: fix incorrect StatusCode parsing

### LINKED ISSUE #3279: Alter exits unexpected without retry
### What type of bug is this?

Unexpected error

### What subsystems are affected?

MetaSrv

### Minimal reproduce step

1. Submits an alter table procedure
2. Injects the network delay between the datanode and metasrv

### What did you expect to see?

Treats requests outdated as success.

### What did you see instead?

[2m2024-02-04T06:29:11.523465Z[0m [31mERROR[0m [1mLocalManager::submit_root_procedure[0m[2m:[0m [2mcommon_procedure::local::runner[0m[2m:[0m Failed to execute procedure metasrv-procedure::AlterTable-dff97557-f564-4f74-9869-2af4ddae37ea, retry: false [3merr[0m[2m=[0m0: Failed to execute procedure due to external error
1: Failed to operate on datanode: peer-2(0.0.0.0:9002), at src/common/meta/src/ddl/utils.rs:38:27
2: External error, at src/client/src/region.rs:57:31 // <- should be source.status_code
3: Failed to request RegionServer, code: Client specified an invalid argument // <- should be source.status_code
4: Schema version doesn't match. Expect 1 but gives 0 // <- should be RequestOutdated

Seems some error overwrite the `StatusCode::RequestOutdated`

### What operating system did you use?

doesn't matter

### What version of GreptimeDB did you use?

main

### Relevant log output and stack trace

_No response_

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

fix incorrect StatusCode parsing

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

## Refer to a related PR or issue link (optional)
close #3279

### CODE REVIEW

**Review by fengjiachun — APPROVED** [review]
LGTM

File: src/common/error/src/status_code.rs [hunk 1]
```diff
@@ -248,6 +209,14 @@ mod tests {
         assert_status_code_display(StatusCode::TableAlreadyExists, "TableAlreadyExists");
     }
 
+    #[test]
+    fn test_from_u32() {
+        for code in StatusCode::iter() {
+            let num = code as u32;
+            assert_eq!(StatusCode::from_u32(num), Some(code));
+        }
```
Comment (waynexia) [inline src/common/error/src/status_code.rs:217]: maybe also assert an out-of-range case?

**Review by waynexia — APPROVED** [review]
LGTM orz
