### PR TITLE
fix: mitigate memory spike during startup

### LINKED ISSUE #3226: Memory spike during startup
### What type of enhancement is this?

Performance

### What does the enhancement do?

During startup, storage engine reads WAL data and decodes it them to [`WalEntry`](https://github.com/GreptimeTeam/greptime-proto/blob/main/proto/greptime/v1/wal.proto#L42-L45)s. 

image

`WalEntry` contains multipe `Mutation`s, each `Mutation` contains multiple `Row`s, and each `Row` contains multiple `Value`s. While decoding `Row`, values are pushed to the vector, resulting continous reallocation, which takes a lot of memory, as shown on the flamegraph.

diff-0-70

This memory consumption spike still appear even we remove the `write_to_memtable` stage. Not sure if change WAL entry encoding from protobuf to Arrow IPC can alleviate it.

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by niebayes**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Previously, we aggregate all mutations from wal and write them into the memtable in a batching manner. Now, the mutations are written into the memtable in a streaming manner. We believe this transition could mitigate the memory spike issue during startup.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

## Refer to a related PR or issue link (optional)
fixes #3226

### CODE REVIEW

File: src/mito2/src/region/opener.rs [hunk 1]
```diff
@@ -427,11 +427,11 @@ pub(crate) async fn replay_memtable<S: LogStore>(
                 .unwrap_or(0);
             region_write_ctx.push_mutation(mutation.op_type, mutation.rows, OptionOutputTx::none());
         }
-    }
 
-    // set next_entry_id and write to memtable.
-    region_write_ctx.set_next_entry_id(last_entry_id + 1);
-    region_write_ctx.write_memtable();
+        // set next_entry_id and write to memtable.
+        region_write_ctx.set_next_entry_id(last_entry_id + 1);
```
Comment (evenyag) [inline src/mito2/src/region/opener.rs:432]: We should set the entry id outside of the loop.

File: src/mito2/src/region/opener.rs [hunk 2]
```diff
@@ -427,11 +427,11 @@ pub(crate) async fn replay_memtable<S: LogStore>(
                 .unwrap_or(0);
             region_write_ctx.push_mutation(mutation.op_type, mutation.rows, OptionOutputTx::none());
         }
-    }
 
-    // set next_entry_id and write to memtable.
-    region_write_ctx.set_next_entry_id(last_entry_id + 1);
-    region_write_ctx.write_memtable();
+        // set next_entry_id and write to memtable.
```
Comment (v0y4g3r) [inline src/mito2/src/region/opener.rs:431]: We should also bring the instantialization of `RegionWriteContext` (line 401) from outside the loop to inside (line 420).

File: src/mito2/src/region/opener.rs (hunk 1 above)
Comment (v0y4g3r) [reply src/mito2/src/region/opener.rs:432]: > We should set the entry id outside of the loop.

There's no need to invoke `set_next_entry_id` again outside the loop, as all mutations are written to memtable and their entry ids are updated to version control.

**Comment by v0y4g3r** [comment]
The memory consumption during WAL replay before and after this PR:

image

**Review by evenyag — APPROVED** [review]
LGTM

**Review by v0y4g3r — APPROVED** [review]
LGTM
