### PR TITLE
fix: add delays in reconcile tests for async cache invalidation

### LINKED ISSUE #7040: Test failures in reconcile_table
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Metasrv

### Minimal reproduce step

Running tests locally shows two tests passed only after retries, indicating flakiness:

```
Summary [ 49.197s] 3991 tests run: 3991 passed (2 flaky), 5 skipped
FLAKY 2/4 [  1.851s] tests-integration tests::reconcile_table::test_reconcile_added_column
FLAKY 2/4 [  1.918s] tests-integration tests::reconcile_table::test_reconcile_dropped_column
```

Errors observed:

```
thread 'tests::reconcile_table::test_reconcile_added_column' panicked at /Users/dennis/programming/rust/greptimedb/src/common/test-util/src/recordbatch.rs:31:5:
assertion `left == right` failed: actual:
+---------------------+-------+-------------+---------+
| ts                  | host  | method_name | latency |
+---------------------+-------+-------------+---------+
| 2025-08-08T20:00:06 | host1 | GetUser     | 103.0   |
| 2025-08-08T20:00:08 | host3 | GetUser     | 105.0   |
+---------------------+-------+-------------+---------+
  left: "+---------------------+-------+-------------+---------+\n| ts                  | host  | method_name | latency |\n+---------------------+-------+-------------+---------+\n| 2025-08-08T20:00:06 | host1 | GetUser     | 103.0   |\n| 2025-08-08T20:00:08 | host3 | GetUser     | 105.0   |\n+---------------------+-------+-------------+---------+"
 right: "+---------------------+-------+-------------+---------+----------------+\n| ts                  | host  | method_name | latency | cloud_provider |\n+---------------------+-------+-------------+---------+----------------+\n| 2025-08-08T20:00:06 | host1 | GetUser     | 103.0   |                |\n| 2025-08-08T20:00:08 | host3 | GetUser     | 105.0   | aws            |\n+---------------------+-------+-------------+---------+----------------+"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'tests::reconcile_table::test_reconcile_dropped_column' panicked at /Users/dennis/programming/rust/greptimedb/src/common/test-util/src/recordbatch.rs:26:75:
called `Result::unwrap()` on an `Err` value: 0: <transparent>, at /Users/dennis/.rustup/toolchains/nightly-2025-05-19-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/task/poll.rs:290:44
1: External(0: External error, at src/query/src/dist_plan/merge_scan.rs:323:22
1: Region query error, at src/frontend/src/instance/region_query.rs:57:14
2: Failed to query, at src/frontend/src/instance/region_query.rs:83:14
3: External error, at src/client/src/region.rs:89:14
4: Failed to do Flight get, code: Internal error
5: Failed to decode DataFusion plan: No field named env. Valid fields are grpc_latencies.ts, grpc_latencies.host, grpc_latencies.method_name, grpc_latencies.latency., at src/client/src/error.rs:173:1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrac
```

These issues should be investigated and fixed.

### What did you expect to see?

Success without retrying

### What did you see instead?

Success after retring

### What operating system did you use?

Not relevant.

### What version of GreptimeDB did you use?

main branch

### Relevant log output and stack trace

```bash

```

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
close #7040

## What's changed and what's your intention?

This PR addresses race conditions in tests caused by asynchronous cache invalidation. Add 1-second sleep delays to allow cache invalidation to complete before asserting query results. Also add logging for mailbox messages in heartbeat responses to improve observability.

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [x] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/frontend/src/heartbeat.rs [hunk 1]
```diff
@@ -104,6 +104,9 @@ impl HeartbeatTask {
                 match resp_stream.message().await {
                     Ok(Some(resp)) => {
                         debug!("Receiving heartbeat response: {:?}", resp);
+                        if let Some(message) = &resp.mailbox_message {
+                            info!("Received mailbox message: {message:?}");
```
Comment (evenyag) [inline src/frontend/src/heartbeat.rs:108]: Will it be too verbose to log in info level?

Comment (WenyXu) [reply src/frontend/src/heartbeat.rs:108]: I think it's worth logging this at the info level. All cache invalidation instructions will be logged, which can be helpful when investigating issues such as cache inconsistencies.

**Review by fengjiachun — APPROVED** [review]

**Review by evenyag — APPROVED** [review]
