### PR TITLE
fix(mito2): accept post-truncate flush for skip-wal tables

### LINKED ISSUE #7856: "Failed to flush region ... is truncated"
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

greptimedb.toml:

```toml
[[region_engine]]
[region_engine.mito]
global_write_buffer_size = "2GB"
```

start greptimedb:

```bash
./greptime standalone start -c greptimedb.toml
```

create table:

```sql
CREATE TABLE IF NOT EXISTS `benchmark_grpc_bulk` (
  `host` STRING NULL,
  `region` STRING NULL,
  `datacenter` STRING NULL,
  `service` STRING NULL,
  `cpu` DOUBLE NULL,
  `memory` DOUBLE NULL,
  `disk_util` DOUBLE NULL,
  `net_in` DOUBLE NULL,
  `net_out` DOUBLE NULL,
  `ts` TIMESTAMP(3) NOT NULL DEFAULT current_timestamp(),
  TIME INDEX (`ts`),
  PRIMARY KEY (`host`, `region`, `datacenter`, `service`)
)

ENGINE=mito
WITH(
  skip_wal = 'true'
)
```

run ingestion-benchmark (https://github.com/killme2008/greptimedb-ingestion-benchmark):

```bash
./ingestion-benchmark -protocols grpc_bulk -concurrency 20
```

then stop (ctrl + c) greptimedb (see the error logs?):

```text
2026-03-24T11:36:47.363434Z  INFO on_query{protocol="mysql"}:mysql::do_query:SqlQueryHandler::do_query:execute_sql:create_table:create_table_inner:create_non_logic_table: operator::statement::ddl: Successfully created table 'greptime.public.benchmark_grpc_bulk' with table id 1024
2026-03-24T11:37:04.177274Z  INFO LocalManager::submit_root_procedure{procedure_name=metasrv-procedure::TruncateTable procedure_id=0546add4-4cbf-445f-aabf-0dc8db225582}: common_procedure::local::runner: Runner metasrv-procedure::TruncateTable-0546add4-4cbf-445f-aabf-0dc8db225582 starts
2026-03-24T11:37:04.177432Z  INFO mito2::worker::handle_truncate: Try to fully truncate region 4398046511104(1024, 0)
2026-03-24T11:37:04.178276Z  INFO mito2::worker::handle_truncate: Complete truncating region: 4398046511104(1024, 0), kind: All { truncated_entry_id: 0, truncated_sequence: 0 }.
2026-03-24T11:37:04.178356Z  INFO LocalManager::submit_root_procedure{procedure_name=metasrv-procedure::TruncateTable procedure_id=0546add4-4cbf-445f-aabf-0dc8db225582}: common_procedure::local::runner: Procedure metasrv-procedure::TruncateTable-0546add4-4cbf-445f-aabf-0dc8db225582 done
2026-03-24T11:37:04.178421Z  INFO LocalManager::submit_root_procedure{procedure_name=metasrv-procedure::TruncateTable procedure_id=0546add4-4cbf-445f-aabf-0dc8db225582}: common_procedure::local::runner: Runner metasrv-procedure::TruncateTable-0546add4-4cbf-445f-aabf-0dc8db225582 exits
2026-03-24T11:37:04.178471Z  INFO sql{protocol="http" request_type="sql"}:SqlQueryHandler::do_query:execute_sql:truncate_table:DdlManager::submit_ddl_task: common_meta::ddl_manager: Table: 1024 is truncated via procedure_id ProcedureId(0546add4-4cbf-445f-aabf-0dc8db225582)
^C2026-03-24T11:37:17.701158Z  INFO cmd: Received SIGINT, shutting down
2026-03-24T11:37:17.701200Z  INFO servers::http: Shutdown HTTP server
2026-03-24T11:37:17.701210Z  INFO servers::server: Service HTTP_SERVER is shutdown!
2026-03-24T11:37:17.701220Z  INFO servers::grpc: Shutdown grpc server
2026-03-24T11:37:17.701228Z  INFO servers::server: Service GRPC_SERVER is shutdown!
2026-03-24T11:37:17.701258Z  INFO servers::server: Postgres server is shutdown.
2026-03-24T11:37:17.701267Z  INFO servers::server: Service POSTGRES_SERVER is shutdown!
2026-03-24T11:37:17.701271Z  INFO servers::server: MySQL server is shutdown.
2026-03-24T11:37:17.701274Z  INFO servers::server: Service MYSQL_SERVER is shutdown!
2026-03-24T11:37:17.701356Z  INFO common_procedure::local: LocalManager is stopped.
2026-03-24T11:37:17.701525Z  INFO mito2::worker::handle_close: Try to close region 4398046511104(1024, 0), worker: 0
2026-03-24T11:37:17.701547Z  INFO mito2::worker::handle_close: Region 4398046511104(1024, 0) has pending data, waiting for flush
^[[A2026-03-24T11:37:31.393231Z  INFO mito2::flush: Successfully flush memtables, region: 4398046511104(1024, 0), reason: Closing, files: [FileId(672277cc-a391-471c-b8e5-1d983f4f6d4d)], series count: 100000, total_rows: 10010000, total_bytes: 475071877, cost: 13.691602883, encoded_part_count: 0, metrics: Metrics { write_type: Flush, iter_source: 1.623667834s, write_batch: 11.251040483s, update_index: 39.265329ms, upload_parquet: 0ns, upload_puffin: 0ns, compact_memtable: 297ns }
2026-03-24T11:37:31.393285Z  INFO mito2::flush: Applying RegionEdit { files_to_add: [FileMeta { region_id: 4398046511104(1024, 0), file_id: 672277cc-a391-471c-b8e5-1d983f4f6d4d , time_range: (2024-01-01 00:00:00+0000, 2024-01-01 02:46:49.999+0000) , level: 0, file_size: 453.1MiB, max_row_group_uncompressed_size: 5.3MiB, num_rows: 10010000, num_row_groups: 98, sequence: 10009001, partition_expr: None, num_series: 100000 }], files_to_remove: [], timestamp_ms: Some(1774352251393), compaction_time_window: None, flushed_entry_id: Some(0), flushed_sequence: Some(10010000), committed_sequence: None } to region 4398046511104(1024, 0), is_staging: false
2026-03-24T11:37:31.393337Z ERROR mito2::flush: Failed to flush region 4398046511104(1024, 0) err=0: Region 4398046511104(1024, 0) is truncated, at src/mito2/src/region.rs:976:17
2026-03-24T11:37:31.393399Z ERROR mito2::flush: Region 4398046511104(1024, 0) failed to flush, cancel all pending tasks err=0: Region 4398046511104(1024, 0) is truncated, at src/mito2/src/region.rs:976:17
2026-03-24T11:37:31.393416Z  WARN datanode::region_server: Failed to close region 4398046511104(1024, 0), err: Failed to flush region 4398046511104(1024, 0)
2026-03-24T11:37:31.393453Z  INFO datanode::region_server: closed 1 regions
2026-03-24T11:37:31.393469Z  INFO datanode::region_server: Region engine metric is stopped
2026-03-24T11:37:31.393547Z  INFO datanode::region_server: Region engine file is stopped
2026-03-24T11:37:31.393557Z  INFO mito2::worker: Stop region worker group
2026-03-24T11:37:31.393683Z  INFO mito2::worker: Stop region worker 0
2026-03-24T11:37:31.393700Z  INFO mito2::worker: Stop region worker 1
2026-03-24T11:37:31.393710Z  INFO mito2::region: Stopped region manifest manager, region_id: 4398046511104(1024, 0)
```

### What did you expect to see?

no error

### What did you see instead?

error

### What operating system did you use?

ubuntu

### What version of GreptimeDB did you use?

rc1

### Relevant log output and stack trace

```bash

```

### PR DESCRIPTION
**Pull request by v0y4g3r**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
Fixes #7856

## What's changed and what's your intention?

Allow flush edits with equal entry ids when flushed sequence advances, so close-time flush after truncate still succeeds for skip-wal regions while stale pre-truncate flushes are rejected. Add a regression test for create->truncate->write->close timing.

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [x] I have written the necessary rustdoc comments.
- [x] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [x] API changes are backward compatible.
- [x] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/mito2/src/region.rs [hunk 1]
```diff
@@ -973,8 +973,23 @@ impl ManifestContext {
...
+                //    increases. This happens in skip-WAL tables where entry id can stay at 0,
+                //    while sequence still advances for post-truncate writes.
+                //
+                // We still reject stale flushes from before truncate:
+                // if entry id is equal and sequence does not advance, the flush is outdated.
+                let is_newer_entry = truncated_entry_id < flushed_entry_id;
+                let is_same_entry_with_newer_sequence = truncated_entry_id == flushed_entry_id
+                    && edit.flushed_sequence.is_some_and(|flushed_sequence| {
+                        manifest.flushed_sequence < flushed_sequence
+                    });
```
Comment (evenyag) [inline src/mito2/src/region.rs:989]: Is it possible that flushed_sequence is None?

Comment (v0y4g3r) [reply src/mito2/src/region.rs:989]: > Is it possible that flushed_sequence is None?

Then this is not a flush edit, we still keep the original condition.
