### PR TITLE
fix(fuzz): sort inserted rows with primary keys and time index

### LINKED ISSUE #4000: Fuzz insert test failed
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Storage Engine

### Minimal reproduce step

1. Hard code the `FuzzInput` to
```
FuzzInput { seed: 266, columns: 19, rows: 3995 }
```
2. Run GreptimeDB
3. Run 
```
cargo fuzz run --fuzz-dir tests-fuzz -D --sanitizer=none fuzz_insert 
```

OR

```sql
CREATE TABLE `teMpora`(
  `raTione` TIMESTAMP(0) TIME INDEX,
  `exPLICABO` FLOAT DEFAULT 0.7750273,
  aut BOOLEAN NULL,
  `QUiA` BOOLEAN,
  `quI` BIGINT NULL,
  `nEscIunt` BIGINT NOT NULL,
  `REICIENdIS` INT NULL,
  `noBis` BIGINT DEFAULT -1522150256160686140,
  `CUmQUE` INT DEFAULT -1268285913,
  `quOS` BIGINT DEFAULT 6724805839282901890,
  odio FLOAT,
  `DOlOREM` BOOLEAN,
  et INT NOT NULL,
  `LIbero` INT,
  `QUis` FLOAT DEFAULT 0.4887722,
  `MiNIMA` FLOAT,
  tempora SMALLINT,
  rem INT NOT NULL,
  `Ea` FLOAT DEFAULT 0.57261616,
  PRIMARY KEY(`LIbero`, tempora, `DOlOREM`, `QUiA`)
) ENGINE = mito;

INSERT INTO
  `teMpora`
VALUES
  (
    '2037-06-27 09:54:36+0000',
    0.3343737,
    false,
    false,
    -4144725995123210844,
    -3082176640087399360,
    1020303571,
    NULL,
    957236357,
    5685825137374556496,
    0.51182777,
    false,
    -108127605,
    240702623,
    0.259059,
    NULL,
    -11743,
    1769219856,
    0.19971871
  );

SELECT
  `raTione`,
  `exPLICABO`,
  aut,
  `QUiA`,
  `quI`,
  `nEscIunt`,
  `REICIENdIS`,
  `noBis`,
  `CUmQUE`,
  `quOS`,
  odio,
  `DOlOREM`,
  et,
  `LIbero`,
  `QUis`,
  `MiNIMA`,
  tempora,
  rem,
  `Ea`
FROM
  `teMpora`
ORDER BY
  `raTione`
```

### What did you expect to see?

Should pass the test

### What did you see instead?

```
...
2024-05-21T06:57:09.5460417Z fuzz test must be succeed: 0: Failed to assert: Expected value: 0.3343737, got: NULL, at /home/runner/work/greptimedb/greptimedb/tests-fuzz/src/validator/row.rs:137:13
...
```

https://github.com/GreptimeTeam/greptimedb/actions/runs/9170138785/job/25211918959?pr=3998

### What operating system did you use?

doesn't matter

### What version of GreptimeDB did you use?

main

### Relevant log output and stack trace

_No response_

### PR DESCRIPTION
**Pull request by CookiePieWw**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

close #4000

## What's changed and what's your intention?

As title. Correct the failed fuzz seed `FuzzInput { seed: 266, columns: 19, rows: 3995 }`

The time index is treated as one of the primary keys for sorting. To compare the `Value::Default` with other values, all the default values in the `insert_expr` is replaced with its original value.

## Checklist

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

### CODE REVIEW

File: tests-fuzz/src/ir.rs [hunk 1]
```diff
@@ -437,6 +439,42 @@ pub fn generate_columns<R: Rng + 'static>(
         .collect()
 }
 
+/// Replace Value::Default with the corresponding default value in the rows for comparison.
+pub fn replace_default(
```
Comment (WenyXu) [inline tests-fuzz/src/ir.rs:443]: How about changing it to `fill_default_value`? @evenyag

**Review by evenyag — APPROVED** [review]

File: tests-fuzz/src/ir.rs (hunk 1 above)
Comment (evenyag) [reply tests-fuzz/src/ir.rs:443]: Both are ok to me.

**Review by WenyXu — APPROVED** [review]
