### PR TITLE
fix: support restart sqlness in distributed mode

### LINKED ISSUE #1442: support sqlness restart in distributed mode
@killme2008 May I ask distributed mode sqlness test support `--- SQLNESS ARG restart=true` or not? I found that remove the restart command in distributed sqlness file passes the test in my local machine. Maybe I thought it's exactly the same test cases between standalone and distributed mode is wrong.

_Originally posted by @lizhemingi in https://github.com/GreptimeTeam/greptimedb/issues/1440#issuecomment-1518926497_

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

- move the `alter_table` case to common dir
- correct the subcommand when restarting distributed mode
- refactor the start and check connection function

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)

Closes #1442

### CODE REVIEW

File: tests/runner/src/env.rs [hunk 1]
```diff
@@ -178,27 +161,42 @@ impl Env {
...
-        let new_server_process = Env::start_server("standalone", &db.ctx, false);
-        *server_process = new_server_process;
 
-        let is_up = util::check_port(SERVER_ADDR.parse().unwrap(), Duration::from_secs(2)).await;
-        if !is_up {
-            Env::stop_server(&mut server_process).await;
-            panic!("Server doesn't up in 10 seconds, quit.")
-        }
+        // check if the server is distributed or standalone
+        let subcommand = if db.frontend_process.is_some() {
```
Comment (killme2008) [inline tests/runner/src/env.rs:193]: It's tricky, why not just add a field to `GreptimeDB` that represents if it's a standalone mode or not?

File: tests/runner/src/env.rs [hunk 2]
```diff
@@ -178,27 +161,42 @@ impl Env {
...
+        let ip_addr = match subcommand {
+            "datanode" => DATANODE_ADDR,
+            "frontend" => SERVER_ADDR,
+            "metasrv" => METASRV_ADDR,
+            "standalone" => SERVER_ADDR,
+            _ => panic!("Unexpected subcommand: {subcommand}"),
+        };
+        if !util::check_port(ip_addr.parse().unwrap(), Duration::from_secs(10)).await {
+            Env::stop_server(&mut process).await;
+            panic!("Frontend doesn't up in 10 seconds, quit.")
```
Comment (MichaelScofield) [inline tests/runner/src/env.rs:181]:
```suggestion
            panic!("{subcommand} doesn't up in 10 seconds, quit.")
```

**Review by MichaelScofield — APPROVED** [review]

File: tests/runner/src/env.rs (hunk 2 above)
Comment (waynexia) [reply tests/runner/src/env.rs:181]: 👍
