### PR TITLE
fix: label_replace and label_join functions when used as sub‐expressions

### LINKED ISSUE #5726: PromQL: crash or 400 error when querying with binary operators and `label_replace`
### What type of bug is this?

Crash

### What subsystems are affected?

Query Engine

## reproduce the crash

start a vector to ingest metrics `vector -c config.toml`

```toml
[sources.my_source_id]
type = "internal_metrics"

[sinks.my_sink_id]
type = "prometheus_remote_write"
inputs = [ "my_source_id" ]
endpoint = "http://127.0.0.1:4000/v1/prometheus/write?db=public"
```

execute PromQL

```
tql eval(1742215047, 1742215747, '10s') {__name__="vector_component_sent_bytes_total", component_kind="sink"} + label_replace(vector(0), "component_kind", "test", "", "")
```

## reproduce the 400 error

ingest some metrics

```
monitor,host=127.0.0.1 cpu=0.1,memory=0.4 1667446797450
monitor,host=127.0.0.2 cpu=0.2,memory=0.3 1667446798450
monitor,host=127.0.0.1 cpu=0.5,memory=0.2 1667446798450
```

eval PromQL

```
tql eval(1667446797, 1667446798, '1m') {__name__="monitor",host="127.0.0.1"} * label_replace(vector(1), "host", "127.0.0.1", "", "")
```

getting following reponse, no error logs from greptime. 
```json
{
    "code": 3000,
    "error": "Internal error during building DataFusion plan: Error during planning: Cannot coerce arithmetic expression Float64 * Utf8 to valid types",
    "execution_time_ms": 1
}
```

### What did you expect to see?

don't crash.

### What did you see instead?

.

### What operating system did you use?

macOS

### What version of GreptimeDB did you use?

0.13.0

### Relevant log output and stack trace

```bash
greptime  | 2025-03-17T13:02:37.558625Z ERROR sql{protocol="http" request_type="sql"}:do_query:plan_tql:plan:plan_pql: common_telemetry::panic_hook: panicked at src/query/src/promql/planner.rs:592:80:
greptime  | called `Option::unwrap()` on a `None` value backtrace=   0: common_telemetry::panic_hook::set_panic_hook::{{closure}}
greptime  |    1: std::panicking::rust_panic_with_hook
greptime  |    2: std::panicking::begin_panic_handler::{{closure}}
greptime  |    3: std::sys::backtrace::__rust_end_short_backtrace
greptime  |    4: rust_begin_unwind
greptime  |    5: core::panicking::panic_fmt
greptime  |    6: core::panicking::panic
greptime  |    7: core::option::unwrap_failed
greptime  |    8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
greptime  |    9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
greptime  |   10: query::promql::planner::PromPlanner::projection_for_each_field_column
greptime  |   11: query::promql::planner::PromPlanner::prom_expr_to_plan::{{closure}}
greptime  |   12: query::planner::DfLogicalPlanner::plan_pql::{{closure}}::{{closure}}
greptime  |   13: <query::planner::DfLogicalPlanner as query::planner::LogicalPlanner>::plan::{{closure}}::{{closure}}
greptime  |   14: <query::planner::DfLogicalPlanner as query::planner::LogicalPlanner>::plan::{{closure}}
greptime  |   15: operator::statement::tql::<impl operator::statement::StatementExecutor>::plan_tql::{{closure}}::{{closure}}
greptime  |   16: operator::statement::tql::<impl operator::statement::StatementExecutor>::plan_tql::{{closure}}
greptime  |   17: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
greptime  |   18: <frontend::instance::Instance as servers::query_handler::sql::SqlQueryHandler>::do_query::{{closure}}
greptime  |   19: <servers::query_handler::sql::ServerSqlQueryHandlerAdapter<E> as servers::query_handler::sql::SqlQueryHandler>::do_query::{{closure}}
greptime  |   20: servers::http::handler::sql::{{closure}}::{{closure}}
greptime  |   21: <F as axum::handler::Handler<(M,T1,T2,T3,T4),S>>::call::{{closure}}
greptime  |   22: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   23: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   24: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
greptime  |   25: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   26: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   28: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
greptime  |   29: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   30: axum::middleware::from_fn::Next::run::{{closure}}
greptime  |   31: <axum::middleware::from_fn::FromFn<F,S,I,(T1,)> as tower_service::Service<http::request::Request<axum_core::body::Body>>>::call::{{closure}}
greptime  |   32: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   33: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   34: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   35: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
greptime  |   36: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   37: axum::middleware::from_fn::Next::run::{{closure}}
greptime  |   38: <axum::middleware::from_fn::FromFn<F,S,I,(T1,)> as tower_service::Service<http::request::Request<axum_core::body::Body>>>::call::{{closure}}
greptime  |   39: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
greptime  |   40: axum::middleware::from_fn::Next::run::{{closure}}
greptime  |   41: <axum::middleware::from_fn::FromFn<F,S,I,(T1,T2)> as tower_service::Service<http::request::Request<axum_core::body::Body>>>::call::{{closure}}
greptime  |   42: <tower::util::either::EitherResponseFuture<A,B> as core::future::future::Future>::poll
greptime  |   43: <tower_http::cors::ResponseFuture<F> as core::future::future::Future>::poll
greptime  |   44: <tower_http::trace::future::ResponseFuture<Fut,C,OnResponseT,OnBodyChunkT,OnEosT,OnFailureT> as core::future::future::Future>::poll
greptime  |   45: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   46: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   47: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
greptime  |   48: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
greptime  |   49: <hyper_util::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
greptime  |   50: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
greptime  |   51: <core::pin::Pin<P> as core::future::future::Future>::poll
greptime  |   52: <core::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
greptime  |   53: <axum::serve::WithGracefulShutdown<L,M,S,F> as core::future::into_future::IntoFuture>::into_future::{{closure}}::{{closure}}
greptime  |   54: tokio::runtime::task::core::Core<T,S>::poll
greptime  |   55: tokio::runtime::task::harness::Harness<T,S>::poll
greptime  |   56: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
greptime  |   57: tokio::runtime::scheduler::multi_thread::worker::Context::run
greptime  |   58: tokio::runtime::context::runtime::enter_runtime
greptime  |   59: tokio::runtime::scheduler::multi_thread::worker::run
greptime  |   60: tokio::runtime::task::core::Core<T,S>::poll
greptime  |   61: tokio::runtime::task::harness::Harness<T,S>::poll
greptime  |   62: tokio::runtime::blocking::pool::Inner::run
greptime  |   63: std::sys::backtrace::__rust_begin_short_backtrace
greptime  |   64: core::ops::function::FnOnce::call_once{{vtable.shim}}
greptime  |   65: std::sys::pal::unix::thread::Thread::new::thread_start
greptime  |   66: <unknown>
greptime  |   67: <unknown>
greptime  |  panic.file="src/query/src/promql/planner.rs" panic.line=592 panic.column=80
```

### LINKED ISSUE #6438: PromQL: Unsupported expr type: filter on multi-value input when using label_replace as input of other expr
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Query Engine

### Minimal reproduce step

For exporter data, this will work:

```promql
label_replace(up{job="node", instance =~ "node_exporter.*|test_.*"}, "endpoint", "$1", "instance", "(.*):.*")
```

When using label_replace as sub query of other expression, it fails

```promql
count(label_replace(up{job="node", instance =~ "node_exporter.*|test_.*"}, "endpoint", "$1", "instance", "(.*):.*") == 0)
```

### What did you expect to see?

This will work for prometheus:

Image

### What did you see instead?

Error message: `Unsupported expr type: filter on multi-value`

### What operating system did you use?

any

### What version of GreptimeDB did you use?

0.14.4 

### Relevant log output and stack trace

```bash

```

### PR DESCRIPTION
**Pull request by killme2008**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

Close #6438 
Close #5726 

## What's changed and what's your intention?

Main changes:

1. Fixes the handling of label_replace and label_join when used as sub‐expressions, updates the planner to emit new tag columns.
2. Adds end‐to‐end tests for these functions.

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [x] I have written the necessary rustdoc comments.
- [x] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [x] API changes are backward compatible.
- [x] Schema or data changes are backward compatible.

### CODE REVIEW

File: src/query/src/promql/planner.rs [hunk 1]
```diff
@@ -1458,21 +1464,25 @@ impl PromPlanner {
...
     ///
-    /// This method will update [PromPlannerContext]'s value fields.
+    /// This method will update [PromPlannerContext]'s fields/tags if needed.
     fn create_function_expr(
         &mut self,
         func: &Function,
         other_input_exprs: Vec<DfExpr>,
         session_state: &SessionState,
-    ) -> Result<Vec<DfExpr>> {
+    ) -> Result<(Vec<DfExpr>, Vec<String>)> {
```
Comment (waynexia) [inline src/query/src/promql/planner.rs]: Looks like this function won't update tags in context, but return it instead?

Comment (killme2008) [reply src/query/src/promql/planner.rs]: ~~Yes, the comment is wrong. Let me fix it.~~

The `tag_columns` are updated when creating label functions. If `dst_label` exists in the tag columns, try removing it at first. The comment is correct.

**Review by evenyag — APPROVED** [review]

File: src/query/src/promql/planner.rs [hunk 2]
```diff
@@ -1605,10 +1615,10 @@ impl PromPlanner {
                     }
                 }
 
-                // Remove it from tag columns
+                // Remove it from tag columns if exists
                 self.ctx.tag_columns.retain(|tag| *tag != dst_label);
```
Comment (sunng87) [inline src/query/src/promql/planner.rs:1619]: if this step still necessary? The tag is removed and added later.

File: tests/cases/standalone/common/promql/label.sql [hunk 3]
```diff
@@ -52,6 +52,23 @@ TQL EVAL (0, 15, '5s') label_replace(test{host="host2"}, "idc", "$2", "idc", "(.
 -- SQLNESS SORT_RESULT 3 1
 TQL EVAL (0, 15, '5s') label_replace(test{host="host2"}, "idc", "", "", "");
 
+-- Issue 5726 --
+-- SQLNESS SORT_RESULT 3 1
+TQL EVAL(0, 15, '5s') label_replace(vector(1), "host", "host1", "", "");
+
+-- SQLNESS SORT_RESULT 3 1
+TQL EVAL(0, 15, '5s') {__name__="test",host="host1"} * label_replace(vector(1), "host", "host1", "", "");
```
Comment (sunng87) [inline tests/cases/standalone/common/promql/label.sql:60]: Add new cases:

src_label exists and regex is empty:
```
TQL EVAL(0, 15, '5s') {__name__="test",host="host1"} * label_replace(vector(1), "host", "host2", "host", "");
```

src_label not exists and regex is empty:
```
TQL EVAL(0, 15, '5s') {__name__="test",host="host1"} * label_replace(vector(1), "addr", "host1", "instance", "");
```

File: src/query/src/promql/planner.rs (hunk 2 above)
Comment (killme2008) [reply src/query/src/promql/planner.rs:1619]: Yes. Since we alias `regex_replace` as `dst_label` when building the function, duplicate column names are not allowed.

We should raise an error here, as Prometheus does:
```
label_replace(up, 'instance', 'a', 'instance', '.*')
````

```
vector cannot contain metrics with the same labelset
```

File: tests/cases/standalone/common/promql/label.sql (hunk 3 above)
Comment (killme2008) [reply tests/cases/standalone/common/promql/label.sql:60]: Added. But they are not addressed in this PR. It's not the same issue with #5726 or #6438 .

~~To address them, `label_replace` requires special handling for the `vector` function~~.

~~We can check if the `src_label` exists before creating the function expression. If it doesn't exists, keep everything unchanged.~~

Comment (killme2008) [reply tests/cases/standalone/common/promql/label.sql:60]: Try my best to fix it in https://github.com/GreptimeTeam/greptimedb/pull/6443/commits/ab960ecf5fbaf332428a0f7300fb3ba53532b65a

File: src/query/src/promql/planner.rs (hunk 2 above)
Comment (killme2008) [reply src/query/src/promql/planner.rs:1619]: Addressed in https://github.com/GreptimeTeam/greptimedb/pull/6443/commits/ab960ecf5fbaf332428a0f7300fb3ba53532b65a

File: tests/cases/standalone/common/promql/label.result [hunk 4]
```diff
@@ -242,6 +229,105 @@ TQL EVAL(0, 15, '5s') {__name__="test",host="host1"} + label_replace(vector(1),
...
+-- Empty regex with not existing source label--
+-- SQLNESS SORT_RESULT 3 1
+TQL EVAL(0, 15, '5s') {__name__="test",host="host1"} * label_replace(vector(1), "host", "host2", "host", "");
+
+++
+++
+
+-- SQLNESS SORT_RESULT 3 1
+TQL EVAL(0, 15, '5s') {__name__="test",host="host1"} * label_replace(vector(1), "addr", "host1", "instance", "");
+
```
Comment (killme2008) [inline tests/cases/standalone/common/promql/label.result:299]: Raise an error now, but Prometheus will ignore it. The binary operator should tolerate this case. cc @waynexia

**Review by sunng87 — APPROVED** [review]

File: tests/cases/standalone/common/promql/label.result (hunk 4 above)
Comment (waynexia) [reply tests/cases/standalone/common/promql/label.result:299]: looks like `addr` is from `label_replace` 🤔

Comment (killme2008) [reply tests/cases/standalone/common/promql/label.result:299]: Yes, and since the left expression lacks it, Prometheus will return empty results.
