### PR TITLE
fix(util): join_path function should not trim leading `/`

### LINKED ISSUE #3212: Unexpected trim behavior of `join_path`
`join_path` function will trim leading `/` in path. So when joining `/a/b` with `c`, the resulting path will be `a/b/c` instead of `/a/b/c`

---
              > Use join_path?

`join_path` does not apply here since it removes leading `/` in path:
https://github.com/GreptimeTeam/greptimedb/blob/75975adcb6a03dc68fa81e2cfe36f30a0a202538/src/object-store/src/util.rs#L81

_Originally posted by @v0y4g3r in https://github.com/GreptimeTeam/greptimedb/pull/3164#discussion_r1461390626_

### PR DESCRIPTION
**Pull request by dalprahcd**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed, and what's your intention?

Replaced `opendal::raw::normalize_path` with own implementation of `normalize_path` in order to fix expected behaviour of not trimming leading `'/'`.

Also fixed some typing errors (I believe) when I was reading the Makefile.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

## Refer to a related PR or issue link (optional)
Closes #3212

### CODE REVIEW

**Comment by dalprahcd** [comment]
@tisonkun you are welcome to review it and let me know about any necessary changes.

File: src/object-store/src/util.rs [hunk 1]
```diff
@@ -78,7 +78,55 @@ pub fn normalize_dir(v: &str) -> String {
...
+
+    // If path is not starting with `\` but it should
+    if !p.starts_with('/') && has_leading {
+        p.insert(0, '/');
+    }
+
+    // If path is not ending with `\` but it should
+    if !p.ends_with('/') && has_trailing {
+        p.push('/');
+    }
```
Comment (tisonkun) [inline src/object-store/src/util.rs:127]:
```suggestion
    if has_leading {
        p.insert(0, '/');
    }

    if has_trailing {
        p.push('/');
    }
```

After `filter not is_empty` and `join`, p is always in form `a/b/c`.

File: src/object-store/src/util.rs [hunk 2]
```diff
@@ -78,7 +78,55 @@ pub fn normalize_dir(v: &str) -> String {
...
+///
+/// Make sure all operation are constructed by normalized path:
+///
+/// - Path endswith `/` means it's a dir path.
+/// - Otherwise, it's a file path.
+///
+/// # Normalize Rules
+///
+/// - All whitespace will be trimmed: ` abc/def ` => `abc/def`
+/// - **(Removed❗️)** ~~ All leading / will be trimmed: `///abc` => `abc`~~
```
Comment (tisonkun) [inline src/object-store/src/util.rs:98]: We don't need this diff comment. You know it because it comes from OpenDAL and we do the diff, but it's meaningless for following developers.

Also, I'm unsure if we should normalize `///abc` to ///abc` or `/abc`. Somehow our inputs should be clean (only `/abc` as input) and we need not worry about it anyway.

@v0y4g3r @evenyag do you remember what behavior we want here? It looks like quite a tribal rule and I'd like to know where/how GreptimeDB depends on this join function.

**Review by tisonkun — COMMENTED** [review]
Thanks for your contribution! Comments inline.

File: src/object-store/src/util.rs (hunk 2 above)
Comment (evenyag) [reply src/object-store/src/util.rs:98]: We could replace most places that use `format!("{}/{}")` to join two object paths with this helper function. We might get `/a//b` if inputs are `/a/` and `b` as `format` always insert a `/` into the result. We can't use `std::path::Path` as we need a path for object stores so we still use `/` as delimiters on Windows.

> Somehow our inputs should be clean (only /abc as input) and we need not worry about it anyway.

We might deal with user inputs so we should sanitize the path.

e.g. The path might be retrieved from a `COPY DATABASE` SQL statement.
https://github.com/GreptimeTeam/greptimedb/pull/3164#discussion_r1461390626

Comment (evenyag) [reply src/object-store/src/util.rs:98]: > We don't need this diff comment.

This follows the comment in `normalize_dir()`. Do we still need them? @v0y4g3r

Comment (v0y4g3r) [reply src/object-store/src/util.rs:98]: > I'm unsure if we should normalize ///abc to ///abc or /abc

This is the desired behavior.

> We don't need this diff comment.

We don't need to explain the difference between this function and opendal's. @dalprahcd just keep the documentation for normilze rules.

File: src/object-store/src/util.rs [hunk 3]
```diff
@@ -78,7 +78,55 @@ pub fn normalize_dir(v: &str) -> String {
...
     let output = format!("{parent}/{child}");
-    opendal::raw::normalize_path(&output)
+    normalize_path(&output)
+}
+
+/// Modified from the `opendal::raw::normalize_path`
+///
+/// # The different
+///
+/// It only keeps `/` ahead if the original path starts with `/`.
```
Comment (v0y4g3r) [inline src/object-store/src/util.rs:88]:
```suggestion
```

File: src/object-store/src/util.rs [hunk 4]
```diff
@@ -78,7 +78,55 @@ pub fn normalize_dir(v: &str) -> String {
...
+        return "/".to_string();
+    }
+
+    let has_leading = path.starts_with('/');
+    let has_trailing = path.ends_with('/');
+
+    let mut p = path
+        .split('/')
+        .filter(|v| !v.is_empty())
+        .collect::<Vec<&str>>()
```
Comment (v0y4g3r) [inline src/object-store/src/util.rs:116]: nitpick:
```suggestion
        .collect::<Vec<_>>()
```

**Review by v0y4g3r — COMMENTED** [review]
Almost LGTM, just some style and doc issues

File: src/object-store/src/util.rs (hunk 1 above)
Comment (dalprahcd) [reply src/object-store/src/util.rs:127]: Making those changes breaks the following unit test: 
```
assert_eq!("/", join_path("", ""));

assertion `left == right` failed
  left: "/"
 right: "//"
```

Because both `has_leading` and `has_trailing` will be set to true for a single `/`, and them both will be inserted again at the end, resulting at `//`, I believe this is not the expected behavior, could you confirm?

Comment (tisonkun) [reply src/object-store/src/util.rs:121]: Thanks for sharing this edge case. You are right that your code is better in such case.

While I'm thinking we may check the input since `join_path("", "")` doesn't seem a valid input for me, you code can handle all the case.

cc @v0y4g3r @evenyag I wonder if we should return error on `join_path("", "")` or assert it won't happen, or return `"/"`.

**Review by tisonkun — APPROVED** [review]
It's good to merge :D

File: src/object-store/src/util.rs [hunk 5]
```diff
@@ -78,7 +78,49 @@ pub fn normalize_dir(v: &str) -> String {
...
+        .filter(|v| !v.is_empty())
+        .collect::<Vec<_>>()
+        .join("/");
+
+    // If path is not starting with `\` but it should
+    if !p.starts_with('/') && has_leading {
+        p.insert(0, '/');
+    }
+
+    // If path is not ending with `\` but it should
```
Comment (evenyag) [inline src/object-store/src/util.rs:118]:
```suggestion
    // If path is not starting with `/` but it should
    if !p.starts_with('/') && has_leading {
        p.insert(0, '/');
    }

    // If path is not ending with `/` but it should
```

File: src/object-store/src/util.rs (hunk 1 above)
Comment (evenyag) [reply src/object-store/src/util.rs:121]: Returning `/` is fine.

**Review by evenyag — APPROVED** [review]
LGTM. Thanks for your contribution!
