### PR TITLE
fix: window inferer

### LINKED ISSUE #2023: abnormal data lead to (almost) dead loop
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

For parquets with range [`(0, 1690189123)`, `(0, 1)`], it will lead to a dead loop on `align_time_spans_to_windows`:

https://github.com/GreptimeTeam/greptimedb/blob/fcff66e03904d80aacb91b8edd4e15240161d264/src/storage/src/window_infer.rs#L126-L135

This loop will loop from 0 to 1690189123 with step 1.

### What operating system did you use?

doesn't matter

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

create two parquet with time range [`(0, 1690189123)`, `(0, 1)`]

### PR DESCRIPTION
**Pull request by v0y4g3r**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

This PR changes the `min_duration_to_window_size` function in window inferer to ensure that the SST file or memtable will only be splitted to at most 128 (2^7) time windows, so that we won't stuck in iterating windows.

## Checklist

- [X]  I have written the necessary rustdoc comments.
- [X]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)

fixes #2023

### CODE REVIEW

File: src/storage/src/window_infer.rs [hunk 1]
```diff
@@ -138,10 +141,12 @@ fn align_time_spans_to_windows(durations: &[(i64, i64)], min_duration: i64) -> H
...
 }
 
-/// Find the most suitable time window size according to the `min_duration` found across all
-/// SST files and memtables through a binary search.
-fn min_duration_to_window_size(min_duration: i64) -> i64 {
-    match TIME_WINDOW_SIZE.binary_search(&min_duration) {
+/// Find the most suitable time window size according to the `min_duration` and `max_duration`
+/// found across all SST files and memtables through a binary search.
+fn duration_to_window_size(min_duration: i64, max_duration: i64) -> i64 {
+    let max_bucket = max_duration >> 7;
```
Comment (waynexia) [inline src/storage/src/window_infer.rs:147]: sugg: Make the `7` a constant

**Review by waynexia — APPROVED** [review]

File: src/storage/src/window_infer.rs (hunk 1 above)
Comment (v0y4g3r) [reply src/storage/src/window_infer.rs:147]: > sugg: Make the `7` a constant

But I don't know what is the appropriate name of this const. `MAX_WINDOW_PER_FILE_EXP`?

**Review by killme2008 — APPROVED** [review]
